export const countries = [
  {
    name: "United States",
    officialName: "United States of America",
    alpha2: "US",
    alpha3: "USA",
    numeric: "840",
    capital: "Washington, D.C.",
    region: "Americas",
    subregion: "Northern America",
    continent: "North America",
    nativeName: "United States",
    languages: ["English"],
    flag: "🇺🇸",
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "1",
    phoneMask: "###-###-#####",
  },
  {
    name: "Canada",
    officialName: "Canada",
    alpha2: "CA",
    alpha3: "CAN",
    numeric: "124",
    capital: "Ottawa",
    region: "Americas",
    subregion: "Northern America",
    continent: "North America",
    nativeName: "Canada",
    languages: ["English", "French"],
    flag: "🇨🇦",
    currency: {
      code: "CAD",
      name: "Canadian dollar",
      symbol: "$",
    },
    phoneCode: "1",
    phoneMask: "###-###-#####",
  },
  {
    name: "Brazil",
    officialName: "Federative Republic of Brazil",
    alpha2: "BR",
    alpha3: "BRA",
    numeric: "076",
    capital: "Brasília",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Brasil",
    languages: ["Portuguese"],
    flag: "🇧🇷",
    currency: {
      code: "BRL",
      name: "Brazilian real",
      symbol: "R$",
    },
    phoneCode: "55",
    phoneMask: "##-#####-#####",
  },
  {
    name: "United Kingdom",
    officialName: "United Kingdom of Great Britain and Northern Ireland",
    alpha2: "GB",
    alpha3: "GBR",
    numeric: "826",
    capital: "London",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "United Kingdom",
    languages: ["English"],
    flag: "🇬🇧",
    currency: {
      code: "GBP",
      name: "British pound",
      symbol: "£",
    },
    phoneCode: "44",
    phoneMask: "####-#######",
  },
  {
    name: "Germany",
    officialName: "Federal Republic of Germany",
    alpha2: "DE",
    alpha3: "DEU",
    numeric: "276",
    capital: "Berlin",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Deutschland",
    languages: ["German"],
    flag: "🇩🇪",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "49",
    phoneMask: "###-########",
  },
  {
    name: "France",
    officialName: "French Republic",
    alpha2: "FR",
    alpha3: "FRA",
    numeric: "250",
    capital: "Paris",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "France",
    languages: ["French"],
    flag: "🇫🇷",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "33",
    phoneMask: "#-##-##-##-###",
  },
  {
    name: "China",
    officialName: "People's Republic of China",
    alpha2: "CN",
    alpha3: "CHN",
    numeric: "156",
    capital: "Beijing",
    region: "Asia",
    subregion: "Eastern Asia",
    continent: "Asia",
    nativeName: "中国",
    languages: ["Chinese"],
    flag: "🇨🇳",
    currency: {
      code: "CNY",
      name: "Chinese yuan",
      symbol: "¥",
    },
    phoneCode: "86",
    phoneMask: "###-####-#####",
  },
  {
    name: "Japan",
    officialName: "Japan",
    alpha2: "JP",
    alpha3: "JPN",
    numeric: "392",
    capital: "Tokyo",
    region: "Asia",
    subregion: "Eastern Asia",
    continent: "Asia",
    nativeName: "日本",
    languages: ["Japanese"],
    flag: "🇯🇵",
    currency: {
      code: "JPY",
      name: "Japanese yen",
      symbol: "¥",
    },
    phoneCode: "81",
    phoneMask: "##-####-#####",
  },
  {
    name: "India",
    officialName: "Republic of India",
    alpha2: "IN",
    alpha3: "IND",
    numeric: "356",
    capital: "New Delhi",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "भारत",
    languages: ["Hindi", "English"],
    flag: "🇮🇳",
    currency: {
      code: "INR",
      name: "Indian rupee",
      symbol: "₹",
    },
    phoneCode: "91",
    phoneMask: "#####-######",
  },
  {
    name: "Australia",
    officialName: "Commonwealth of Australia",
    alpha2: "AU",
    alpha3: "AUS",
    numeric: "036",
    capital: "Canberra",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    continent: "Oceania",
    nativeName: "Australia",
    languages: ["English"],
    flag: "🇦🇺",
    currency: {
      code: "AUD",
      name: "Australian dollar",
      symbol: "$",
    },
    phoneCode: "61",
    phoneMask: "#-####-#####",
  },
  {
    name: "South Africa",
    officialName: "Republic of South Africa",
    alpha2: "ZA",
    alpha3: "ZAF",
    numeric: "710",
    capital: "Pretoria",
    region: "Africa",
    subregion: "Southern Africa",
    continent: "Africa",
    nativeName: "Afrika Borwa",
    languages: [
      "Afrikaans",
      "English",
      "Zulu",
      "Xhosa",
      "Swati",
      "Tswana",
      "Southern Sotho",
      "Venda",
      "Tsonga",
      "Northern Sotho",
      "Ndebele",
    ],
    flag: "🇿🇦",
    currency: {
      code: "ZAR",
      name: "South African rand",
      symbol: "R",
    },
    phoneCode: "27",
    phoneMask: "##-###-#####",
  },
  {
    name: "Nigeria",
    officialName: "Federal Republic of Nigeria",
    alpha2: "NG",
    alpha3: "NGA",
    numeric: "566",
    capital: "Abuja",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Nigeria",
    languages: ["English"],
    flag: "🇳🇬",
    currency: {
      code: "NGN",
      name: "Nigerian naira",
      symbol: "₦",
    },
    phoneCode: "234",
    phoneMask: "###-###-#####",
  },
  {
    name: "Mexico",
    officialName: "United Mexican States",
    alpha2: "MX",
    alpha3: "MEX",
    numeric: "484",
    capital: "Mexico City",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "México",
    languages: ["Spanish"],
    flag: "🇲🇽",
    currency: {
      code: "MXN",
      name: "Mexican peso",
      symbol: "$",
    },
    phoneCode: "52",
    phoneMask: "###-###-#####",
  },
  {
    name: "Russia",
    officialName: "Russian Federation",
    alpha2: "RU",
    alpha3: "RUS",
    numeric: "643",
    capital: "Moscow",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Россия",
    languages: ["Russian"],
    flag: "🇷🇺",
    currency: {
      code: "RUB",
      name: "Russian ruble",
      symbol: "₽",
    },
    phoneCode: "7",
    phoneMask: "###-###-#####",
  },
  {
    name: "Saudi Arabia",
    officialName: "Kingdom of Saudi Arabia",
    alpha2: "SA",
    alpha3: "SAU",
    numeric: "682",
    capital: "Riyadh",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "المملكة العربية السعودية",
    languages: ["Arabic"],
    flag: "🇸🇦",
    currency: {
      code: "SAR",
      name: "Saudi riyal",
      symbol: "ر.س",
    },
    phoneCode: "966",
    phoneMask: "#-####-#####",
  },
  {
    name: "Afghanistan",
    officialName: "Islamic Republic of Afghanistan",
    alpha2: "AF",
    alpha3: "AFG",
    numeric: "004",
    capital: "Kabul",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "افغانستان",
    languages: ["Pashto", "Dari"],
    flag: "🇦🇫",
    currency: {
      code: "AFN",
      name: "Afghan afghani",
      symbol: "؋",
    },
    phoneCode: "93",
    phoneMask: "##-###-#####",
  },
  {
    name: "Albania",
    officialName: "Republic of Albania",
    alpha2: "AL",
    alpha3: "ALB",
    numeric: "008",
    capital: "Tirana",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Shqipëria",
    languages: ["Albanian"],
    flag: "🇦🇱",
    currency: {
      code: "ALL",
      name: "Albanian lek",
      symbol: "L",
    },
    phoneCode: "355",
    phoneMask: "##-###-#####",
  },
  {
    name: "Algeria",
    officialName: "People's Democratic Republic of Algeria",
    alpha2: "DZ",
    alpha3: "DZA",
    numeric: "012",
    capital: "Algiers",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "الجزائر",
    languages: ["Arabic"],
    flag: "🇩🇿",
    currency: {
      code: "DZD",
      name: "Algerian dinar",
      symbol: "د.ج",
    },
    phoneCode: "213",
    phoneMask: "##-###-#####",
  },
  {
    name: "Andorra",
    officialName: "Principality of Andorra",
    alpha2: "AD",
    alpha3: "AND",
    numeric: "020",
    capital: "Andorra la Vella",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Andorra",
    languages: ["Catalan"],
    flag: "🇦🇩",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "376",
    phoneMask: "###-####",
  },
  {
    name: "Angola",
    officialName: "Republic of Angola",
    alpha2: "AO",
    alpha3: "AGO",
    numeric: "024",
    capital: "Luanda",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Angola",
    languages: ["Portuguese"],
    flag: "🇦🇴",
    currency: {
      code: "AOA",
      name: "Angolan kwanza",
      symbol: "Kz",
    },
    phoneCode: "244",
    phoneMask: "###-###-####",
  },
  {
    name: "Antigua and Barbuda",
    officialName: "Antigua and Barbuda",
    alpha2: "AG",
    alpha3: "ATG",
    numeric: "028",
    capital: "Saint John's",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Antigua and Barbuda",
    languages: ["English"],
    flag: "🇦🇬",
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "1-268",
    phoneMask: "+1-268-###-#####",
  },
  {
    name: "Argentina",
    officialName: "Argentine Republic",
    alpha2: "AR",
    alpha3: "ARG",
    numeric: "032",
    capital: "Buenos Aires",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Argentina",
    languages: ["Spanish"],
    flag: "🇦🇷",
    currency: {
      code: "ARS",
      name: "Argentine peso",
      symbol: "$",
    },
    phoneCode: "54",
    phoneMask: "###-###-#####",
  },
  {
    name: "Armenia",
    officialName: "Republic of Armenia",
    alpha2: "AM",
    alpha3: "ARM",
    numeric: "051",
    capital: "Yerevan",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "Հայաստան",
    languages: ["Armenian"],
    flag: "🇦🇲",
    currency: {
      code: "AMD",
      name: "Armenian dram",
      symbol: "֏",
    },
    phoneCode: "374",
    phoneMask: "##-###-####",
  },
  {
    name: "Austria",
    officialName: "Republic of Austria",
    alpha2: "AT",
    alpha3: "AUT",
    numeric: "040",
    capital: "Vienna",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Österreich",
    languages: ["German"],
    flag: "🇦🇹",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "43",
    phoneMask: "###-###-####",
  },
  {
    name: "Azerbaijan",
    officialName: "Republic of Azerbaijan",
    alpha2: "AZ",
    alpha3: "AZE",
    numeric: "031",
    capital: "Baku",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "Azərbaycan",
    languages: ["Azerbaijani"],
    flag: "🇦🇿",
    currency: {
      code: "AZN",
      name: "Azerbaijani manat",
      symbol: "₼",
    },
    phoneCode: "994",
    phoneMask: "##-###-#####",
  },
  {
    name: "Bahamas",
    officialName: "Commonwealth of The Bahamas",
    alpha2: "BS",
    alpha3: "BHS",
    numeric: "044",
    capital: "Nassau",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Bahamas",
    languages: ["English"],
    flag: "🇧🇸",
    currency: {
      code: "BSD",
      name: "Bahamian dollar",
      symbol: "$",
    },
    phoneCode: "1-242",
    phoneMask: "+1-242-###-#####",
  },
  {
    name: "Bahrain",
    officialName: "Kingdom of Bahrain",
    alpha2: "BH",
    alpha3: "BHR",
    numeric: "048",
    capital: "Manama",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "البحرين",
    languages: ["Arabic"],
    flag: "🇧🇭",
    currency: {
      code: "BHD",
      name: "Bahraini dinar",
      symbol: ".د.ب",
    },
    phoneCode: "973",
    phoneMask: "####-#####",
  },
  {
    name: "Bangladesh",
    officialName: "People's Republic of Bangladesh",
    alpha2: "BD",
    alpha3: "BGD",
    numeric: "050",
    capital: "Dhaka",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "বাংলাদেশ",
    languages: ["Bengali"],
    flag: "🇧🇩",
    currency: {
      code: "BDT",
      name: "Bangladeshi taka",
      symbol: "৳",
    },
    phoneCode: "880",
    phoneMask: "####-#######",
  },
  {
    name: "Barbados",
    officialName: "Barbados",
    alpha2: "BB",
    alpha3: "BRB",
    numeric: "052",
    capital: "Bridgetown",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Barbados",
    languages: ["English"],
    flag: "🇧🇧",
    currency: {
      code: "BBD",
      name: "Barbadian dollar",
      symbol: "$",
    },
    phoneCode: "1-246",
    phoneMask: "+1-246-###-#####",
  },
  {
    name: "Belarus",
    officialName: "Republic of Belarus",
    alpha2: "BY",
    alpha3: "BLR",
    numeric: "112",
    capital: "Minsk",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Беларусь",
    languages: ["Belarusian", "Russian"],
    flag: "🇧🇾",
    currency: {
      code: "BYN",
      name: "Belarusian ruble",
      symbol: "Br",
    },
    phoneCode: "375",
    phoneMask: "##-###-#####",
  },
  {
    name: "Belgium",
    officialName: "Kingdom of Belgium",
    alpha2: "BE",
    alpha3: "BEL",
    numeric: "056",
    capital: "Brussels",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "België",
    languages: ["Dutch", "French", "German"],
    flag: "🇧🇪",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "32",
    phoneMask: "###-###-####",
  },
  {
    name: "Belize",
    officialName: "Belize",
    alpha2: "BZ",
    alpha3: "BLZ",
    numeric: "084",
    capital: "Belmopan",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Belize",
    languages: ["English"],
    flag: "🇧🇿",
    currency: {
      code: "BZD",
      name: "Belize dollar",
      symbol: "$",
    },
    phoneCode: "501",
    phoneMask: "###-#####",
  },
  {
    name: "Benin",
    officialName: "Republic of Benin",
    alpha2: "BJ",
    alpha3: "BEN",
    numeric: "204",
    capital: "Porto-Novo",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Bénin",
    languages: ["French"],
    flag: "🇧🇯",
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "229",
    phoneMask: "##-###-####",
  },
  {
    name: "Bhutan",
    officialName: "Kingdom of Bhutan",
    alpha2: "BT",
    alpha3: "BTN",
    numeric: "064",
    capital: "Thimphu",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "འབྲུག",
    languages: ["Dzongkha"],
    flag: "🇧🇹",
    currency: {
      code: "BTN",
      name: "Bhutanese ngultrum",
      symbol: "Nu.",
    },
    phoneCode: "975",
    phoneMask: "#-###-#####",
  },
  {
    name: "Bolivia",
    officialName: "Plurinational State of Bolivia",
    alpha2: "BO",
    alpha3: "BOL",
    numeric: "068",
    capital: "Sucre",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Bolivia",
    languages: ["Spanish", "Quechua", "Aymara"],
    flag: "🇧🇴",
    currency: {
      code: "BOB",
      name: "Bolivian boliviano",
      symbol: "Bs.",
    },
    phoneCode: "591",
    phoneMask: "#-###-#####",
  },
  {
    name: "Bosnia and Herzegovina",
    officialName: "Bosnia and Herzegovina",
    alpha2: "BA",
    alpha3: "BIH",
    numeric: "070",
    capital: "Sarajevo",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Bosna i Hercegovina",
    languages: ["Bosnian", "Croatian", "Serbian"],
    flag: "🇧🇦",
    currency: {
      code: "BAM",
      name: "Bosnia and Herzegovina convertible mark",
      symbol: "KM",
    },
    phoneCode: "387",
    phoneMask: "##-###-####",
  },
  {
    name: "Botswana",
    officialName: "Republic of Botswana",
    alpha2: "BW",
    alpha3: "BWA",
    numeric: "072",
    capital: "Gaborone",
    region: "Africa",
    subregion: "Southern Africa",
    continent: "Africa",
    nativeName: "Botswana",
    languages: ["English", "Tswana"],
    flag: "🇧🇼",
    currency: {
      code: "BWP",
      name: "Botswana pula",
      symbol: "P",
    },
    phoneCode: "267",
    phoneMask: "##-###-####",
  },
  {
    name: "Brunei",
    officialName: "Nation of Brunei, the Abode of Peace",
    alpha2: "BN",
    alpha3: "BRN",
    numeric: "096",
    capital: "Bandar Seri Begawan",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Brunei",
    languages: ["Malay"],
    flag: "🇧🇳",
    currency: {
      code: "BND",
      name: "Brunei dollar",
      symbol: "$",
    },
    phoneCode: "673",
    phoneMask: "###-#####",
  },
  {
    name: "Bulgaria",
    officialName: "Republic of Bulgaria",
    alpha2: "BG",
    alpha3: "BGR",
    numeric: "100",
    capital: "Sofia",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "България",
    languages: ["Bulgarian"],
    flag: "🇧🇬",
    currency: {
      code: "BGN",
      name: "Bulgarian lev",
      symbol: "лв",
    },
    phoneCode: "359",
    phoneMask: "###-###-####",
  },
  {
    name: "Burkina Faso",
    officialName: "Burkina Faso",
    alpha2: "BF",
    alpha3: "BFA",
    numeric: "854",
    capital: "Ouagadougou",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Burkina Faso",
    languages: ["French"],
    flag: "🇧🇫",
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "226",
    phoneMask: "##-###-####",
  },
  {
    name: "Burundi",
    officialName: "Republic of Burundi",
    alpha2: "BI",
    alpha3: "BDI",
    numeric: "108",
    capital: "Gitega",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Uburundi",
    languages: ["Kirundi", "French", "English"],
    flag: "🇧🇮",
    currency: {
      code: "BIF",
      name: "Burundian franc",
      symbol: "FBu",
    },
    phoneCode: "257",
    phoneMask: "##-###-####",
  },
  {
    name: "Cabo Verde",
    officialName: "Republic of Cabo Verde",
    alpha2: "CV",
    alpha3: "CPV",
    numeric: "132",
    capital: "Praia",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Cabo Verde",
    languages: ["Portuguese"],
    flag: "🇨🇻",
    currency: {
      code: "CVE",
      name: "Cape Verdean escudo",
      symbol: "$",
    },
    phoneCode: "238",
    phoneMask: "###-#####",
  },
  {
    name: "Cambodia",
    officialName: "Kingdom of Cambodia",
    alpha2: "KH",
    alpha3: "KHM",
    numeric: "116",
    capital: "Phnom Penh",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "កម្ពុជា",
    languages: ["Khmer"],
    flag: "🇰🇭",
    currency: {
      code: "KHR",
      name: "Cambodian riel",
      symbol: "៛",
    },
    phoneCode: "855",
    phoneMask: "##-###-####",
  },
  {
    name: "Cameroon",
    officialName: "Republic of Cameroon",
    alpha2: "CM",
    alpha3: "CMR",
    numeric: "120",
    capital: "Yaoundé",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Cameroun",
    languages: ["English", "French"],
    flag: "🇨🇲",
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "237",
    phoneMask: "###-###-####",
  },
  {
    name: "Central African Republic",
    officialName: "Central African Republic",
    alpha2: "CF",
    alpha3: "CAF",
    numeric: "140",
    capital: "Bangui",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "République centrafricaine",
    languages: ["French", "Sango"],
    flag: "🇨🇫",
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "236",
    phoneMask: "##-###-####",
  },
  {
    name: "Chad",
    officialName: "Republic of Chad",
    alpha2: "TD",
    alpha3: "TCD",
    numeric: "148",
    capital: "N'Djamena",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Tchad",
    languages: ["French", "Arabic"],
    flag: "🇹🇩",
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "235",
    phoneMask: "##-###-####",
  },
  {
    name: "Chile",
    officialName: "Republic of Chile",
    alpha2: "CL",
    alpha3: "CHL",
    numeric: "152",
    capital: "Santiago",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Chile",
    languages: ["Spanish"],
    flag: "🇨🇱",
    currency: {
      code: "CLP",
      name: "Chilean peso",
      symbol: "$",
    },
    phoneCode: "56",
    phoneMask: "#-####-#####",
  },
  {
    name: "Colombia",
    officialName: "Republic of Colombia",
    alpha2: "CO",
    alpha3: "COL",
    numeric: "170",
    capital: "Bogotá",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Colombia",
    languages: ["Spanish"],
    flag: "🇨🇴",
    currency: {
      code: "COP",
      name: "Colombian peso",
      symbol: "$",
    },
    phoneCode: "57",
    phoneMask: "###-###-#####",
  },
  {
    name: "Comoros",
    officialName: "Union of the Comoros",
    alpha2: "KM",
    alpha3: "COM",
    numeric: "174",
    capital: "Moroni",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "جزر القمر",
    languages: ["Arabic", "French", "Comorian"],
    flag: "🇰🇲",
    currency: {
      code: "KMF",
      name: "Comorian franc",
      symbol: "CF",
    },
    phoneCode: "269",
    phoneMask: "###-#####",
  },
  {
    name: "Congo (Congo-Brazzaville)",
    officialName: "Republic of the Congo",
    alpha2: "CG",
    alpha3: "COG",
    numeric: "178",
    capital: "Brazzaville",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Congo",
    languages: ["French"],
    flag: "🇨🇬",
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "242",
    phoneMask: "##-###-#####",
  },
  {
    name: "Congo (Congo-Kinshasa)",
    officialName: "Democratic Republic of the Congo",
    alpha2: "CD",
    alpha3: "COD",
    numeric: "180",
    capital: "Kinshasa",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "République démocratique du Congo",
    languages: ["French"],
    flag: "🇨🇩",
    currency: {
      code: "CDF",
      name: "Congolese franc",
      symbol: "FC",
    },
    phoneCode: "243",
    phoneMask: "##-###-#####",
  },
  {
    name: "Costa Rica",
    officialName: "Republic of Costa Rica",
    alpha2: "CR",
    alpha3: "CRI",
    numeric: "188",
    capital: "San José",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Costa Rica",
    languages: ["Spanish"],
    flag: "🇨🇷",
    currency: {
      code: "CRC",
      name: "Costa Rican colón",
      symbol: "₡",
    },
    phoneCode: "506",
    phoneMask: "####-#####",
  },
  {
    name: "Croatia",
    officialName: "Republic of Croatia",
    alpha2: "HR",
    alpha3: "HRV",
    numeric: "191",
    capital: "Zagreb",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Hrvatska",
    languages: ["Croatian"],
    flag: "🇭🇷",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "385",
    phoneMask: "##-###-#####",
  },
  {
    name: "Cuba",
    officialName: "Republic of Cuba",
    alpha2: "CU",
    alpha3: "CUB",
    numeric: "192",
    capital: "Havana",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Cuba",
    languages: ["Spanish"],
    flag: "🇨🇺",
    currency: {
      code: "CUP",
      name: "Cuban peso",
      symbol: "$",
    },
    phoneCode: "53",
    phoneMask: "#-###-#####",
  },
  {
    name: "Cyprus",
    officialName: "Republic of Cyprus",
    alpha2: "CY",
    alpha3: "CYP",
    numeric: "196",
    capital: "Nicosia",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "Κύπρος",
    languages: ["Greek", "Turkish"],
    flag: "🇨🇾",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "357",
    phoneMask: "##-###-####",
  },
  {
    name: "Czech Republic",
    officialName: "Czech Republic",
    alpha2: "CZ",
    alpha3: "CZE",
    numeric: "203",
    capital: "Prague",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Česko",
    languages: ["Czech"],
    flag: "🇨🇿",
    currency: {
      code: "CZK",
      name: "Czech koruna",
      symbol: "Kč",
    },
    phoneCode: "420",
    phoneMask: "###-###-####",
  },
  {
    name: "Denmark",
    officialName: "Kingdom of Denmark",
    alpha2: "DK",
    alpha3: "DNK",
    numeric: "208",
    capital: "Copenhagen",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Danmark",
    languages: ["Danish"],
    flag: "🇩🇰",
    currency: {
      code: "DKK",
      name: "Danish krone",
      symbol: "kr",
    },
    phoneCode: "45",
    phoneMask: "##-##-##-###",
  },
  {
    name: "Djibouti",
    officialName: "Republic of Djibouti",
    alpha2: "DJ",
    alpha3: "DJI",
    numeric: "262",
    capital: "Djibouti",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "جيبوتي",
    languages: ["French", "Arabic"],
    flag: "🇩🇯",
    currency: {
      code: "DJF",
      name: "Djiboutian franc",
      symbol: "Fdj",
    },
    phoneCode: "253",
    phoneMask: "##-###-####",
  },
  {
    name: "Dominica",
    officialName: "Commonwealth of Dominica",
    alpha2: "DM",
    alpha3: "DMA",
    numeric: "212",
    capital: "Roseau",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Dominica",
    languages: ["English"],
    flag: "🇩🇲",
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "1-767",
    phoneMask: "+1-767-###-#####",
  },
  {
    name: "Dominican Republic",
    officialName: "Dominican Republic",
    alpha2: "DO",
    alpha3: "DOM",
    numeric: "214",
    capital: "Santo Domingo",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "República Dominicana",
    languages: ["Spanish"],
    flag: "🇩🇴",
    currency: {
      code: "DOP",
      name: "Dominican peso",
      symbol: "$",
    },
    phoneCode: "1-809",
    phoneMask: "+1-809-###-#####",
  },
  {
    name: "Ecuador",
    officialName: "Republic of Ecuador",
    alpha2: "EC",
    alpha3: "ECU",
    numeric: "218",
    capital: "Quito",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Ecuador",
    languages: ["Spanish"],
    flag: "🇪🇨",
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "593",
    phoneMask: "##-###-#####",
  },
  {
    name: "Egypt",
    officialName: "Arab Republic of Egypt",
    alpha2: "EG",
    alpha3: "EGY",
    numeric: "818",
    capital: "Cairo",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "مصر",
    languages: ["Arabic"],
    flag: "🇪🇬",
    currency: {
      code: "EGP",
      name: "Egyptian pound",
      symbol: "£",
    },
    phoneCode: "20",
    phoneMask: "###-###-#####",
  },
  {
    name: "El Salvador",
    officialName: "Republic of El Salvador",
    alpha2: "SV",
    alpha3: "SLV",
    numeric: "222",
    capital: "San Salvador",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "El Salvador",
    languages: ["Spanish"],
    flag: "🇸🇻",
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "503",
    phoneMask: "####-#####",
  },
  {
    name: "Equatorial Guinea",
    officialName: "Republic of Equatorial Guinea",
    alpha2: "GQ",
    alpha3: "GNQ",
    numeric: "226",
    capital: "Malabo",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Guinea Ecuatorial",
    languages: ["Spanish", "French", "Portuguese"],
    flag: "🇬🇶",
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "240",
    phoneMask: "###-###-####",
  },
  {
    name: "Eritrea",
    officialName: "State of Eritrea",
    alpha2: "ER",
    alpha3: "ERI",
    numeric: "232",
    capital: "Asmara",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "ኤርትራ",
    languages: ["Tigrinya", "Arabic", "English"],
    flag: "🇪🇷",
    currency: {
      code: "ERN",
      name: "Eritrean nakfa",
      symbol: "Nfk",
    },
    phoneCode: "291",
    phoneMask: "#-###-####",
  },
  {
    name: "Estonia",
    officialName: "Republic of Estonia",
    alpha2: "EE",
    alpha3: "EST",
    numeric: "233",
    capital: "Tallinn",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Eesti",
    languages: ["Estonian"],
    flag: "🇪🇪",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "372",
    phoneMask: "####-#####",
  },
  {
    name: "Eswatini",
    officialName: "Kingdom of Eswatini",
    alpha2: "SZ",
    alpha3: "SWZ",
    numeric: "748",
    capital: "Mbabane",
    region: "Africa",
    subregion: "Southern Africa",
    continent: "Africa",
    nativeName: "eSwatini",
    languages: ["English", "Swati"],
    flag: "🇸🇿",
    currency: {
      code: "SZL",
      name: "Swazi lilangeni",
      symbol: "L",
    },
    phoneCode: "268",
    phoneMask: "####-#####",
  },
  {
    name: "Ethiopia",
    officialName: "Federal Democratic Republic of Ethiopia",
    alpha2: "ET",
    alpha3: "ETH",
    numeric: "231",
    capital: "Addis Ababa",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "ኢትዮጵያ",
    languages: ["Amharic"],
    flag: "🇪🇹",
    currency: {
      code: "ETB",
      name: "Ethiopian birr",
      symbol: "Br",
    },
    phoneCode: "251",
    phoneMask: "##-###-#####",
  },
  {
    name: "Fiji",
    officialName: "Republic of Fiji",
    alpha2: "FJ",
    alpha3: "FJI",
    numeric: "242",
    capital: "Suva",
    region: "Oceania",
    subregion: "Melanesia",
    continent: "Oceania",
    nativeName: "Viti",
    languages: ["English", "Fijian", "Hindi"],
    flag: "🇫🇯",
    currency: {
      code: "FJD",
      name: "Fijian dollar",
      symbol: "$",
    },
    phoneCode: "679",
    phoneMask: "###-#####",
  },
  {
    name: "Finland",
    officialName: "Republic of Finland",
    alpha2: "FI",
    alpha3: "FIN",
    numeric: "246",
    capital: "Helsinki",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Suomi",
    languages: ["Finnish", "Swedish"],
    flag: "🇫🇮",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "358",
    phoneMask: "##-###-#####",
  },
  {
    name: "Gabon",
    officialName: "Gabonese Republic",
    alpha2: "GA",
    alpha3: "GAB",
    numeric: "266",
    capital: "Libreville",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Gabon",
    languages: ["French"],
    flag: "🇬🇦",
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "241",
    phoneMask: "#-###-####",
  },
  {
    name: "Gambia",
    officialName: "Republic of The Gambia",
    alpha2: "GM",
    alpha3: "GMB",
    numeric: "270",
    capital: "Banjul",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Gambia",
    languages: ["English"],
    flag: "🇬🇲",
    currency: {
      code: "GMD",
      name: "Gambian dalasi",
      symbol: "D",
    },
    phoneCode: "220",
    phoneMask: "###-#####",
  },
  {
    name: "Georgia",
    officialName: "Georgia",
    alpha2: "GE",
    alpha3: "GEO",
    numeric: "268",
    capital: "Tbilisi",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "საქართველო",
    languages: ["Georgian"],
    flag: "🇬🇪",
    currency: {
      code: "GEL",
      name: "Georgian lari",
      symbol: "₾",
    },
    phoneCode: "995",
    phoneMask: "###-###-####",
  },
  {
    name: "Ghana",
    officialName: "Republic of Ghana",
    alpha2: "GH",
    alpha3: "GHA",
    numeric: "288",
    capital: "Accra",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Ghana",
    languages: ["English"],
    flag: "🇬🇭",
    currency: {
      code: "GHS",
      name: "Ghanaian cedi",
      symbol: "₵",
    },
    phoneCode: "233",
    phoneMask: "##-###-#####",
  },
  {
    name: "Greece",
    officialName: "Hellenic Republic",
    alpha2: "GR",
    alpha3: "GRC",
    numeric: "300",
    capital: "Athens",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Ελλάδα",
    languages: ["Greek"],
    flag: "🇬🇷",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "30",
    phoneMask: "###-###-#####",
  },
  {
    name: "Grenada",
    officialName: "Grenada",
    alpha2: "GD",
    alpha3: "GRD",
    numeric: "308",
    capital: "St. George's",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Grenada",
    languages: ["English"],
    flag: "🇬🇩",
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "1-473",
    phoneMask: "+1-473-###-#####",
  },
  {
    name: "Guatemala",
    officialName: "Republic of Guatemala",
    alpha2: "GT",
    alpha3: "GTM",
    numeric: "320",
    capital: "Guatemala City",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Guatemala",
    languages: ["Spanish"],
    flag: "🇬🇹",
    currency: {
      code: "GTQ",
      name: "Guatemalan quetzal",
      symbol: "Q",
    },
    phoneCode: "502",
    phoneMask: "####-#####",
  },
  {
    name: "Guinea",
    officialName: "Republic of Guinea",
    alpha2: "GN",
    alpha3: "GIN",
    numeric: "324",
    capital: "Conakry",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Guinée",
    languages: ["French"],
    flag: "🇬🇳",
    currency: {
      code: "GNF",
      name: "Guinean franc",
      symbol: "FG",
    },
    phoneCode: "224",
    phoneMask: "###-###-####",
  },
  {
    name: "Guinea-Bissau",
    officialName: "Republic of Guinea-Bissau",
    alpha2: "GW",
    alpha3: "GNB",
    numeric: "624",
    capital: "Bissau",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Guiné-Bissau",
    languages: ["Portuguese"],
    flag: "🇬🇼",
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "245",
    phoneMask: "###-###-####",
  },
  {
    name: "Guyana",
    officialName: "Co-operative Republic of Guyana",
    alpha2: "GY",
    alpha3: "GUY",
    numeric: "328",
    capital: "Georgetown",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Guyana",
    languages: ["English"],
    flag: "🇬🇾",
    currency: {
      code: "GYD",
      name: "Guyanese dollar",
      symbol: "$",
    },
    phoneCode: "592",
    phoneMask: "###-#####",
  },
  {
    name: "Haiti",
    officialName: "Republic of Haiti",
    alpha2: "HT",
    alpha3: "HTI",
    numeric: "332",
    capital: "Port-au-Prince",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Haïti",
    languages: ["French", "Haitian Creole"],
    flag: "🇭🇹",
    currency: {
      code: "HTG",
      name: "Haitian gourde",
      symbol: "G",
    },
    phoneCode: "509",
    phoneMask: "####-#####",
  },
  {
    name: "Honduras",
    officialName: "Republic of Honduras",
    alpha2: "HN",
    alpha3: "HND",
    numeric: "340",
    capital: "Tegucigalpa",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Honduras",
    languages: ["Spanish"],
    flag: "🇭🇳",
    currency: {
      code: "HNL",
      name: "Honduran lempira",
      symbol: "L",
    },
    phoneCode: "504",
    phoneMask: "####-#####",
  },
  {
    name: "Hungary",
    officialName: "Hungary",
    alpha2: "HU",
    alpha3: "HUN",
    numeric: "348",
    capital: "Budapest",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Magyarország",
    languages: ["Hungarian"],
    flag: "🇭🇺",
    currency: {
      code: "HUF",
      name: "Hungarian forint",
      symbol: "Ft",
    },
    phoneCode: "36",
    phoneMask: "##-###-#####",
  },
  {
    name: "Iceland",
    officialName: "Republic of Iceland",
    alpha2: "IS",
    alpha3: "ISL",
    numeric: "352",
    capital: "Reykjavik",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Ísland",
    languages: ["Icelandic"],
    flag: "🇮🇸",
    currency: {
      code: "ISK",
      name: "Icelandic króna",
      symbol: "kr",
    },
    phoneCode: "354",
    phoneMask: "###-#####",
  },
  {
    name: "Indonesia",
    officialName: "Republic of Indonesia",
    alpha2: "ID",
    alpha3: "IDN",
    numeric: "360",
    capital: "Jakarta",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Indonesia",
    languages: ["Indonesian"],
    flag: "🇮🇩",
    currency: {
      code: "IDR",
      name: "Indonesian rupiah",
      symbol: "Rp",
    },
    phoneCode: "62",
    phoneMask: "###-###-#####",
  },
  {
    name: "Iran",
    officialName: "Islamic Republic of Iran",
    alpha2: "IR",
    alpha3: "IRN",
    numeric: "364",
    capital: "Tehran",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "ایران",
    languages: ["Persian"],
    flag: "🇮🇷",
    currency: {
      code: "IRR",
      name: "Iranian rial",
      symbol: "﷼",
    },
    phoneCode: "98",
    phoneMask: "###-###-#####",
  },
  {
    name: "Iraq",
    officialName: "Republic of Iraq",
    alpha2: "IQ",
    alpha3: "IRQ",
    numeric: "368",
    capital: "Baghdad",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "العراق",
    languages: ["Arabic", "Kurdish"],
    flag: "🇮🇶",
    currency: {
      code: "IQD",
      name: "Iraqi dinar",
      symbol: "ع.د",
    },
    phoneCode: "964",
    phoneMask: "###-###-#####",
  },
  {
    name: "Ireland",
    officialName: "Republic of Ireland",
    alpha2: "IE",
    alpha3: "IRL",
    numeric: "372",
    capital: "Dublin",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Éire",
    languages: ["English", "Irish"],
    flag: "🇮🇪",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "353",
    phoneMask: "##-###-#####",
  },
  {
    name: "Israel",
    officialName: "State of Israel",
    alpha2: "IL",
    alpha3: "ISR",
    numeric: "376",
    capital: "Jerusalem",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "ישראל",
    languages: ["Hebrew", "Arabic"],
    flag: "🇮🇱",
    currency: {
      code: "ILS",
      name: "Israeli new shekel",
      symbol: "₪",
    },
    phoneCode: "972",
    phoneMask: "##-###-#####",
  },
  {
    name: "Italy",
    officialName: "Italian Republic",
    alpha2: "IT",
    alpha3: "ITA",
    numeric: "380",
    capital: "Rome",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Italia",
    languages: ["Italian"],
    flag: "🇮🇹",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "39",
    phoneMask: "###-###-#####",
  },
  {
    name: "Jamaica",
    officialName: "Jamaica",
    alpha2: "JM",
    alpha3: "JAM",
    numeric: "388",
    capital: "Kingston",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Jamaica",
    languages: ["English"],
    flag: "🇯🇲",
    currency: {
      code: "JMD",
      name: "Jamaican dollar",
      symbol: "$",
    },
    phoneCode: "1-876",
    phoneMask: "+1-876-###-#####",
  },
  {
    name: "Jordan",
    officialName: "Hashemite Kingdom of Jordan",
    alpha2: "JO",
    alpha3: "JOR",
    numeric: "400",
    capital: "Amman",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "الأردن",
    languages: ["Arabic"],
    flag: "🇯🇴",
    currency: {
      code: "JOD",
      name: "Jordanian dinar",
      symbol: "د.ا",
    },
    phoneCode: "962",
    phoneMask: "#-####-#####",
  },
  {
    name: "Kazakhstan",
    officialName: "Republic of Kazakhstan",
    alpha2: "KZ",
    alpha3: "KAZ",
    numeric: "398",
    capital: "Astana",
    region: "Asia",
    subregion: "Central Asia",
    continent: "Asia",
    nativeName: "Қазақстан",
    languages: ["Kazakh", "Russian"],
    flag: "🇰🇿",
    currency: {
      code: "KZT",
      name: "Kazakhstani tenge",
      symbol: "₸",
    },
    phoneCode: "7",
    phoneMask: "###-###-#####",
  },
  {
    name: "Kenya",
    officialName: "Republic of Kenya",
    alpha2: "KE",
    alpha3: "KEN",
    numeric: "404",
    capital: "Nairobi",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Kenya",
    languages: ["English", "Swahili"],
    flag: "🇰🇪",
    currency: {
      code: "KES",
      name: "Kenyan shilling",
      symbol: "KSh",
    },
    phoneCode: "254",
    phoneMask: "###-###-####",
  },
  {
    name: "Kiribati",
    officialName: "Republic of Kiribati",
    alpha2: "KI",
    alpha3: "KIR",
    numeric: "296",
    capital: "Tarawa",
    region: "Oceania",
    subregion: "Micronesia",
    continent: "Oceania",
    nativeName: "Kiribati",
    languages: ["English", "Gilbertese"],
    flag: "🇰🇮",
    currency: {
      code: "AUD",
      name: "Australian dollar",
      symbol: "$",
    },
    phoneCode: "686",
    phoneMask: "######",
  },
  {
    name: "Kuwait",
    officialName: "State of Kuwait",
    alpha2: "KW",
    alpha3: "KWT",
    numeric: "414",
    capital: "Kuwait City",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "الكويت",
    languages: ["Arabic"],
    flag: "🇰🇼",
    currency: {
      code: "KWD",
      name: "Kuwaiti dinar",
      symbol: "د.ك",
    },
    phoneCode: "965",
    phoneMask: "####-#####",
  },
  {
    name: "Kyrgyzstan",
    officialName: "Kyrgyz Republic",
    alpha2: "KG",
    alpha3: "KGZ",
    numeric: "417",
    capital: "Bishkek",
    region: "Asia",
    subregion: "Central Asia",
    continent: "Asia",
    nativeName: "Кыргызстан",
    languages: ["Kyrgyz", "Russian"],
    flag: "🇰🇬",
    currency: {
      code: "KGS",
      name: "Kyrgyzstani som",
      symbol: "с",
    },
    phoneCode: "996",
    phoneMask: "###-###-####",
  },
  {
    name: "Laos",
    officialName: "Lao People's Democratic Republic",
    alpha2: "LA",
    alpha3: "LAO",
    numeric: "418",
    capital: "Vientiane",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "ລາວ",
    languages: ["Lao"],
    flag: "🇱🇦",
    currency: {
      code: "LAK",
      name: "Lao kip",
      symbol: "₭",
    },
    phoneCode: "856",
    phoneMask: "##-###-#####",
  },
  {
    name: "Latvia",
    officialName: "Republic of Latvia",
    alpha2: "LV",
    alpha3: "LVA",
    numeric: "428",
    capital: "Riga",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Latvija",
    languages: ["Latvian"],
    flag: "🇱🇻",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "371",
    phoneMask: "####-#####",
  },
  {
    name: "Lebanon",
    officialName: "Lebanese Republic",
    alpha2: "LB",
    alpha3: "LBN",
    numeric: "422",
    capital: "Beirut",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "لبنان",
    languages: ["Arabic", "French"],
    flag: "🇱🇧",
    currency: {
      code: "LBP",
      name: "Lebanese pound",
      symbol: "ل.ل",
    },
    phoneCode: "961",
    phoneMask: "##-###-####",
  },
  {
    name: "Lesotho",
    officialName: "Kingdom of Lesotho",
    alpha2: "LS",
    alpha3: "LSO",
    numeric: "426",
    capital: "Maseru",
    region: "Africa",
    subregion: "Southern Africa",
    continent: "Africa",
    nativeName: "Lesotho",
    languages: ["English", "Sesotho"],
    flag: "🇱🇸",
    currency: {
      code: "LSL",
      name: "Lesotho loti",
      symbol: "L",
    },
    phoneCode: "266",
    phoneMask: "####-#####",
  },
  {
    name: "Liberia",
    officialName: "Republic of Liberia",
    alpha2: "LR",
    alpha3: "LBR",
    numeric: "430",
    capital: "Monrovia",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Liberia",
    languages: ["English"],
    flag: "🇱🇷",
    currency: {
      code: "LRD",
      name: "Liberian dollar",
      symbol: "$",
    },
    phoneCode: "231",
    phoneMask: "##-###-#####",
  },
  {
    name: "Libya",
    officialName: "State of Libya",
    alpha2: "LY",
    alpha3: "LBY",
    numeric: "434",
    capital: "Tripoli",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "ليبيا",
    languages: ["Arabic"],
    flag: "🇱🇾",
    currency: {
      code: "LYD",
      name: "Libyan dinar",
      symbol: "ل.د",
    },
    phoneCode: "218",
    phoneMask: "##-###-#####",
  },
  {
    name: "Liechtenstein",
    officialName: "Principality of Liechtenstein",
    alpha2: "LI",
    alpha3: "LIE",
    numeric: "438",
    capital: "Vaduz",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Liechtenstein",
    languages: ["German"],
    flag: "🇱🇮",
    currency: {
      code: "CHF",
      name: "Swiss franc",
      symbol: "CHF",
    },
    phoneCode: "423",
    phoneMask: "###-###-####",
  },
  {
    name: "Lithuania",
    officialName: "Republic of Lithuania",
    alpha2: "LT",
    alpha3: "LTU",
    numeric: "440",
    capital: "Vilnius",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Lietuva",
    languages: ["Lithuanian"],
    flag: "🇱🇹",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "370",
    phoneMask: "###-###-###",
  },
  {
    name: "Luxembourg",
    officialName: "Grand Duchy of Luxembourg",
    alpha2: "LU",
    alpha3: "LUX",
    numeric: "442",
    capital: "Luxembourg",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Lëtzebuerg",
    languages: ["French", "German", "Luxembourgish"],
    flag: "🇱🇺",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "352",
    phoneMask: "###-###-####",
  },
  {
    name: "Madagascar",
    officialName: "Republic of Madagascar",
    alpha2: "MG",
    alpha3: "MDG",
    numeric: "450",
    capital: "Antananarivo",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Madagasikara",
    languages: ["Malagasy", "French"],
    flag: "🇲🇬",
    currency: {
      code: "MGA",
      name: "Malagasy ariary",
      symbol: "Ar",
    },
    phoneCode: "261",
    phoneMask: "##-###-#####",
  },
  {
    name: "Malawi",
    officialName: "Republic of Malawi",
    alpha2: "MW",
    alpha3: "MWI",
    numeric: "454",
    capital: "Lilongwe",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Malawi",
    languages: ["English", "Chewa"],
    flag: "🇲🇼",
    currency: {
      code: "MWK",
      name: "Malawian kwacha",
      symbol: "MK",
    },
    phoneCode: "265",
    phoneMask: "#-###-#####",
  },
  {
    name: "Malaysia",
    officialName: "Malaysia",
    alpha2: "MY",
    alpha3: "MYS",
    numeric: "458",
    capital: "Kuala Lumpur",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Malaysia",
    languages: ["Malay"],
    flag: "🇲🇾",
    currency: {
      code: "MYR",
      name: "Malaysian ringgit",
      symbol: "RM",
    },
    phoneCode: "60",
    phoneMask: "##-###-#####",
  },
  {
    name: "Maldives",
    officialName: "Republic of Maldives",
    alpha2: "MV",
    alpha3: "MDV",
    numeric: "462",
    capital: "Malé",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "ދިވެހިރާއްޖެ",
    languages: ["Dhivehi"],
    flag: "🇲🇻",
    currency: {
      code: "MVR",
      name: "Maldivian rufiyaa",
      symbol: "Rf",
    },
    phoneCode: "960",
    phoneMask: "###-#####",
  },
  {
    name: "Mali",
    officialName: "Republic of Mali",
    alpha2: "ML",
    alpha3: "MLI",
    numeric: "466",
    capital: "Bamako",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Mali",
    languages: ["French"],
    flag: "🇲🇱",
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "223",
    phoneMask: "####-#####",
  },
  {
    name: "Malta",
    officialName: "Republic of Malta",
    alpha2: "MT",
    alpha3: "MLT",
    numeric: "470",
    capital: "Valletta",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Malta",
    languages: ["Maltese", "English"],
    flag: "🇲🇹",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "356",
    phoneMask: "####-#####",
  },
  {
    name: "Marshall Islands",
    officialName: "Republic of the Marshall Islands",
    alpha2: "MH",
    alpha3: "MHL",
    numeric: "584",
    capital: "Majuro",
    region: "Oceania",
    subregion: "Micronesia",
    continent: "Oceania",
    nativeName: "M̧ajeļ",
    languages: ["English", "Marshallese"],
    flag: "🇲🇭",
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "692",
    phoneMask: "###-#####",
  },
  {
    name: "Mauritania",
    officialName: "Islamic Republic of Mauritania",
    alpha2: "MR",
    alpha3: "MRT",
    numeric: "478",
    capital: "Nouakchott",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "موريتانيا",
    languages: ["Arabic"],
    flag: "🇲🇷",
    currency: {
      code: "MRU",
      name: "Mauritanian ouguiya",
      symbol: "UM",
    },
    phoneCode: "222",
    phoneMask: "##-###-####",
  },
  {
    name: "Mauritius",
    officialName: "Republic of Mauritius",
    alpha2: "MU",
    alpha3: "MUS",
    numeric: "480",
    capital: "Port Louis",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Maurice",
    languages: ["English", "French"],
    flag: "🇲🇺",
    currency: {
      code: "MUR",
      name: "Mauritian rupee",
      symbol: "₨",
    },
    phoneCode: "230",
    phoneMask: "####-#####",
  },
  {
    name: "Micronesia",
    officialName: "Federated States of Micronesia",
    alpha2: "FM",
    alpha3: "FSM",
    numeric: "583",
    capital: "Palikir",
    region: "Oceania",
    subregion: "Micronesia",
    continent: "Oceania",
    nativeName: "Micronesia",
    languages: ["English"],
    flag: "🇫🇲",
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "691",
    phoneMask: "###-#####",
  },
  {
    name: "Moldova",
    officialName: "Republic of Moldova",
    alpha2: "MD",
    alpha3: "MDA",
    numeric: "498",
    capital: "Chișinău",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Moldova",
    languages: ["Romanian"],
    flag: "🇲🇩",
    currency: {
      code: "MDL",
      name: "Moldovan leu",
      symbol: "L",
    },
    phoneCode: "373",
    phoneMask: "####-#####",
  },
  {
    name: "Monaco",
    officialName: "Principality of Monaco",
    alpha2: "MC",
    alpha3: "MCO",
    numeric: "492",
    capital: "Monaco",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Monaco",
    languages: ["French"],
    flag: "🇲🇨",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "377",
    phoneMask: "##-###-####",
  },
  {
    name: "Mongolia",
    officialName: "Mongolia",
    alpha2: "MN",
    alpha3: "MNG",
    numeric: "496",
    capital: "Ulaanbaatar",
    region: "Asia",
    subregion: "Eastern Asia",
    continent: "Asia",
    nativeName: "Монгол Улс",
    languages: ["Mongolian"],
    flag: "🇲🇳",
    currency: {
      code: "MNT",
      name: "Mongolian tögrög",
      symbol: "₮",
    },
    phoneCode: "976",
    phoneMask: "##-###-####",
  },
  {
    name: "Montenegro",
    officialName: "Montenegro",
    alpha2: "ME",
    alpha3: "MNE",
    numeric: "499",
    capital: "Podgorica",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Crna Gora",
    languages: ["Montenegrin"],
    flag: "🇲🇪",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "382",
    phoneMask: "##-###-####",
  },
  {
    name: "Morocco",
    officialName: "Kingdom of Morocco",
    alpha2: "MA",
    alpha3: "MAR",
    numeric: "504",
    capital: "Rabat",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "المغرب",
    languages: ["Arabic", "Berber"],
    flag: "🇲🇦",
    currency: {
      code: "MAD",
      name: "Moroccan dirham",
      symbol: "د.م.",
    },
    phoneCode: "212",
    phoneMask: "##-###-#####",
  },
  {
    name: "Mozambique",
    officialName: "Republic of Mozambique",
    alpha2: "MZ",
    alpha3: "MOZ",
    numeric: "508",
    capital: "Maputo",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Moçambique",
    languages: ["Portuguese"],
    flag: "🇲🇿",
    currency: {
      code: "MZN",
      name: "Mozambican metical",
      symbol: "MT",
    },
    phoneCode: "258",
    phoneMask: "##-###-####",
  },
  {
    name: "Myanmar",
    officialName: "Republic of the Union of Myanmar",
    alpha2: "MM",
    alpha3: "MMR",
    numeric: "104",
    capital: "Naypyidaw",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "မြန်မာ",
    languages: ["Burmese"],
    flag: "🇲🇲",
    currency: {
      code: "MMK",
      name: "Myanmar kyat",
      symbol: "K",
    },
    phoneCode: "95",
    phoneMask: "##-###-#####",
  },
  {
    name: "Namibia",
    officialName: "Republic of Namibia",
    alpha2: "NA",
    alpha3: "NAM",
    numeric: "516",
    capital: "Windhoek",
    region: "Africa",
    subregion: "Southern Africa",
    continent: "Africa",
    nativeName: "Namibia",
    languages: ["English"],
    flag: "🇳🇦",
    currency: {
      code: "NAD",
      name: "Namibian dollar",
      symbol: "$",
    },
    phoneCode: "264",
    phoneMask: "##-###-#####",
  },
  {
    name: "Nauru",
    officialName: "Republic of Nauru",
    alpha2: "NR",
    alpha3: "NRU",
    numeric: "520",
    capital: "Yaren",
    region: "Oceania",
    subregion: "Micronesia",
    continent: "Oceania",
    nativeName: "Nauru",
    languages: ["English", "Nauruan"],
    flag: "🇳🇷",
    currency: {
      code: "AUD",
      name: "Australian dollar",
      symbol: "$",
    },
    phoneCode: "674",
    phoneMask: "###-#####",
  },
  {
    name: "Nepal",
    officialName: "Federal Democratic Republic of Nepal",
    alpha2: "NP",
    alpha3: "NPL",
    numeric: "524",
    capital: "Kathmandu",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "नेपाल",
    languages: ["Nepali"],
    flag: "🇳🇵",
    currency: {
      code: "NPR",
      name: "Nepalese rupee",
      symbol: "₨",
    },
    phoneCode: "977",
    phoneMask: "##-###-#####",
  },
  {
    name: "Netherlands",
    officialName: "Kingdom of the Netherlands",
    alpha2: "NL",
    alpha3: "NLD",
    numeric: "528",
    capital: "Amsterdam",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Nederland",
    languages: ["Dutch"],
    flag: "🇳🇱",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "31",
    phoneMask: "##-###-#####",
  },
  {
    name: "New Zealand",
    officialName: "New Zealand",
    alpha2: "NZ",
    alpha3: "NZL",
    numeric: "554",
    capital: "Wellington",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    continent: "Oceania",
    nativeName: "Aotearoa",
    languages: ["English", "Māori"],
    flag: "🇳🇿",
    currency: {
      code: "NZD",
      name: "New Zealand dollar",
      symbol: "$",
    },
    phoneCode: "64",
    phoneMask: "###-###-####",
  },
  {
    name: "Nicaragua",
    officialName: "Republic of Nicaragua",
    alpha2: "NI",
    alpha3: "NIC",
    numeric: "558",
    capital: "Managua",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Nicaragua",
    languages: ["Spanish"],
    flag: "🇳🇮",
    currency: {
      code: "NIO",
      name: "Nicaraguan córdoba",
      symbol: "C$",
    },
    phoneCode: "505",
    phoneMask: "####-#####",
  },
  {
    name: "Niger",
    officialName: "Republic of Niger",
    alpha2: "NE",
    alpha3: "NER",
    numeric: "562",
    capital: "Niamey",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Niger",
    languages: ["French"],
    flag: "🇳🇪",
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "227",
    phoneMask: "##-###-####",
  },
  {
    name: "North Korea",
    officialName: "Democratic People's Republic of Korea",
    alpha2: "KP",
    alpha3: "PRK",
    numeric: "408",
    capital: "Pyongyang",
    region: "Asia",
    subregion: "Eastern Asia",
    continent: "Asia",
    nativeName: "조선",
    languages: ["Korean"],
    flag: "🇰🇵",
    currency: {
      code: "KPW",
      name: "North Korean won",
      symbol: "₩",
    },
    phoneCode: "850",
    phoneMask: "###-###-####",
  },
  {
    name: "North Macedonia",
    officialName: "Republic of North Macedonia",
    alpha2: "MK",
    alpha3: "MKD",
    numeric: "807",
    capital: "Skopje",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Северна Македонија",
    languages: ["Macedonian"],
    flag: "🇲🇰",
    currency: {
      code: "MKD",
      name: "Macedonian denar",
      symbol: "ден",
    },
    phoneCode: "389",
    phoneMask: "##-###-####",
  },
  {
    name: "Norway",
    officialName: "Kingdom of Norway",
    alpha2: "NO",
    alpha3: "NOR",
    numeric: "578",
    capital: "Oslo",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Norge",
    languages: ["Norwegian"],
    flag: "🇳🇴",
    currency: {
      code: "NOK",
      name: "Norwegian krone",
      symbol: "kr",
    },
    phoneCode: "47",
    phoneMask: "###-##-####",
  },
  {
    name: "Oman",
    officialName: "Sultanate of Oman",
    alpha2: "OM",
    alpha3: "OMN",
    numeric: "512",
    capital: "Muscat",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "عمان",
    languages: ["Arabic"],
    flag: "🇴🇲",
    currency: {
      code: "OMR",
      name: "Omani rial",
      symbol: "ر.ع.",
    },
    phoneCode: "968",
    phoneMask: "####-#####",
  },
  {
    name: "Pakistan",
    officialName: "Islamic Republic of Pakistan",
    alpha2: "PK",
    alpha3: "PAK",
    numeric: "586",
    capital: "Islamabad",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "پاکستان",
    languages: ["Urdu", "English"],
    flag: "🇵🇰",
    currency: {
      code: "PKR",
      name: "Pakistani rupee",
      symbol: "₨",
    },
    phoneCode: "92",
    phoneMask: "###-###-#####",
  },
  {
    name: "Palau",
    officialName: "Republic of Palau",
    alpha2: "PW",
    alpha3: "PLW",
    numeric: "585",
    capital: "Ngerulmud",
    region: "Oceania",
    subregion: "Micronesia",
    continent: "Oceania",
    nativeName: "Belau",
    languages: ["English", "Palauan"],
    flag: "🇵🇼",
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "680",
    phoneMask: "###-#####",
  },
  {
    name: "Panama",
    officialName: "Republic of Panama",
    alpha2: "PA",
    alpha3: "PAN",
    numeric: "591",
    capital: "Panama City",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Panamá",
    languages: ["Spanish"],
    flag: "🇵🇦",
    currency: {
      code: "PAB",
      name: "Panamanian balboa",
      symbol: "B/.",
    },
    phoneCode: "507",
    phoneMask: "####-#####",
  },
  {
    name: "Papua New Guinea",
    officialName: "Independent State of Papua New Guinea",
    alpha2: "PG",
    alpha3: "PNG",
    numeric: "598",
    capital: "Port Moresby",
    region: "Oceania",
    subregion: "Melanesia",
    continent: "Oceania",
    nativeName: "Papua Niugini",
    languages: ["English", "Tok Pisin", "Hiri Motu"],
    flag: "🇵🇬",
    currency: {
      code: "PGK",
      name: "Papua New Guinean kina",
      symbol: "K",
    },
    phoneCode: "675",
    phoneMask: "###-#####",
  },
  {
    name: "Paraguay",
    officialName: "Republic of Paraguay",
    alpha2: "PY",
    alpha3: "PRY",
    numeric: "600",
    capital: "Asunción",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Paraguay",
    languages: ["Spanish", "Guarani"],
    flag: "🇵🇾",
    currency: {
      code: "PYG",
      name: "Paraguayan guaraní",
      symbol: "₲",
    },
    phoneCode: "595",
    phoneMask: "###-###-####",
  },
  {
    name: "Peru",
    officialName: "Republic of Peru",
    alpha2: "PE",
    alpha3: "PER",
    numeric: "604",
    capital: "Lima",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Perú",
    languages: ["Spanish", "Quechua", "Aymara"],
    flag: "🇵🇪",
    currency: {
      code: "PEN",
      name: "Peruvian sol",
      symbol: "S/.",
    },
    phoneCode: "51",
    phoneMask: "###-###-####",
  },
  {
    name: "Philippines",
    officialName: "Republic of the Philippines",
    alpha2: "PH",
    alpha3: "PHL",
    numeric: "608",
    capital: "Manila",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Pilipinas",
    languages: ["Filipino", "English"],
    flag: "🇵🇭",
    currency: {
      code: "PHP",
      name: "Philippine peso",
      symbol: "₱",
    },
    phoneCode: "63",
    phoneMask: "###-###-#####",
  },
  {
    name: "Poland",
    officialName: "Republic of Poland",
    alpha2: "PL",
    alpha3: "POL",
    numeric: "616",
    capital: "Warsaw",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Polska",
    languages: ["Polish"],
    flag: "🇵🇱",
    currency: {
      code: "PLN",
      name: "Polish złoty",
      symbol: "zł",
    },
    phoneCode: "48",
    phoneMask: "###-###-####",
  },
  {
    name: "Portugal",
    officialName: "Portuguese Republic",
    alpha2: "PT",
    alpha3: "PRT",
    numeric: "620",
    capital: "Lisbon",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Portugal",
    languages: ["Portuguese"],
    flag: "🇵🇹",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "351",
    phoneMask: "###-###-####",
  },
  {
    name: "Qatar",
    officialName: "State of Qatar",
    alpha2: "QA",
    alpha3: "QAT",
    numeric: "634",
    capital: "Doha",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "قطر",
    languages: ["Arabic"],
    flag: "🇶🇦",
    currency: {
      code: "QAR",
      name: "Qatari riyal",
      symbol: "ر.ق",
    },
    phoneCode: "974",
    phoneMask: "####-#####",
  },
  {
    name: "Romania",
    officialName: "Romania",
    alpha2: "RO",
    alpha3: "ROU",
    numeric: "642",
    capital: "Bucharest",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "România",
    languages: ["Romanian"],
    flag: "🇷🇴",
    currency: {
      code: "RON",
      name: "Romanian leu",
      symbol: "lei",
    },
    phoneCode: "40",
    phoneMask: "###-###-####",
  },
  {
    name: "Rwanda",
    officialName: "Republic of Rwanda",
    alpha2: "RW",
    alpha3: "RWA",
    numeric: "646",
    capital: "Kigali",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Rwanda",
    languages: ["Kinyarwanda", "English", "French"],
    flag: "🇷🇼",
    currency: {
      code: "RWF",
      name: "Rwandan franc",
      symbol: "FRw",
    },
    phoneCode: "250",
    phoneMask: "###-###-####",
  },
  {
    name: "Saint Kitts and Nevis",
    officialName: "Federation of Saint Christopher and Nevis",
    alpha2: "KN",
    alpha3: "KNA",
    numeric: "659",
    capital: "Basseterre",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Saint Kitts and Nevis",
    languages: ["English"],
    flag: "🇰🇳",
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "1-869",
    phoneMask: "+1-869-###-#####",
  },
  {
    name: "Saint Lucia",
    officialName: "Saint Lucia",
    alpha2: "LC",
    alpha3: "LCA",
    numeric: "662",
    capital: "Castries",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Saint Lucia",
    languages: ["English"],
    flag: "🇱🇨",
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "1-758",
    phoneMask: "+1-758-###-#####",
  },
  {
    name: "Saint Vincent and the Grenadines",
    officialName: "Saint Vincent and the Grenadines",
    alpha2: "VC",
    alpha3: "VCT",
    numeric: "670",
    capital: "Kingstown",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Saint Vincent and the Grenadines",
    languages: ["English"],
    flag: "🇻🇨",
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "1-784",
    phoneMask: "+1-784-###-#####",
  },
  {
    name: "Samoa",
    officialName: "Independent State of Samoa",
    alpha2: "WS",
    alpha3: "WSM",
    numeric: "882",
    capital: "Apia",
    region: "Oceania",
    subregion: "Polynesia",
    continent: "Oceania",
    nativeName: "Sāmoa",
    languages: ["Samoan", "English"],
    flag: "🇼🇸",
    currency: {
      code: "WST",
      name: "Samoan tālā",
      symbol: "T",
    },
    phoneCode: "685",
    phoneMask: "######",
  },
  {
    name: "San Marino",
    officialName: "Republic of San Marino",
    alpha2: "SM",
    alpha3: "SMR",
    numeric: "674",
    capital: "San Marino",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "San Marino",
    languages: ["Italian"],
    flag: "🇸🇲",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "378",
    phoneMask: "####-#######",
  },
  {
    name: "Sao Tome and Principe",
    officialName: "Democratic Republic of Sao Tome and Principe",
    alpha2: "ST",
    alpha3: "STP",
    numeric: "678",
    capital: "São Tomé",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "São Tomé e Príncipe",
    languages: ["Portuguese"],
    flag: "🇸🇹",
    currency: {
      code: "STN",
      name: "São Tomé and Príncipe dobra",
      symbol: "Db",
    },
    phoneCode: "239",
    phoneMask: "###-#####",
  },
  {
    name: "Senegal",
    officialName: "Republic of Senegal",
    alpha2: "SN",
    alpha3: "SEN",
    numeric: "686",
    capital: "Dakar",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Sénégal",
    languages: ["French"],
    flag: "🇸🇳",
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "221",
    phoneMask: "##-###-#####",
  },
  {
    name: "Serbia",
    officialName: "Republic of Serbia",
    alpha2: "RS",
    alpha3: "SRB",
    numeric: "688",
    capital: "Belgrade",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Србија",
    languages: ["Serbian"],
    flag: "🇷🇸",
    currency: {
      code: "RSD",
      name: "Serbian dinar",
      symbol: "din.",
    },
    phoneCode: "381",
    phoneMask: "##-###-#####",
  },
  {
    name: "Seychelles",
    officialName: "Republic of Seychelles",
    alpha2: "SC",
    alpha3: "SYC",
    numeric: "690",
    capital: "Victoria",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Sesel",
    languages: ["English", "French", "Seychellois Creole"],
    flag: "🇸🇨",
    currency: {
      code: "SCR",
      name: "Seychellois rupee",
      symbol: "₨",
    },
    phoneCode: "248",
    phoneMask: "####-####",
  },
  {
    name: "Sierra Leone",
    officialName: "Republic of Sierra Leone",
    alpha2: "SL",
    alpha3: "SLE",
    numeric: "694",
    capital: "Freetown",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Sierra Leone",
    languages: ["English"],
    flag: "🇸🇱",
    currency: {
      code: "SLL",
      name: "Sierra Leonean leone",
      symbol: "Le",
    },
    phoneCode: "232",
    phoneMask: "##-###-####",
  },
  {
    name: "Singapore",
    officialName: "Republic of Singapore",
    alpha2: "SG",
    alpha3: "SGP",
    numeric: "702",
    capital: "Singapore",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Singapore",
    languages: ["English", "Malay", "Mandarin", "Tamil"],
    flag: "🇸🇬",
    currency: {
      code: "SGD",
      name: "Singapore dollar",
      symbol: "$",
    },
    phoneCode: "65",
    phoneMask: "####-#####",
  },
  {
    name: "Slovakia",
    officialName: "Slovak Republic",
    alpha2: "SK",
    alpha3: "SVK",
    numeric: "703",
    capital: "Bratislava",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Slovensko",
    languages: ["Slovak"],
    flag: "🇸🇰",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "421",
    phoneMask: "###-###-####",
  },
  {
    name: "Slovenia",
    officialName: "Republic of Slovenia",
    alpha2: "SI",
    alpha3: "SVN",
    numeric: "705",
    capital: "Ljubljana",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Slovenija",
    languages: ["Slovenian"],
    flag: "🇸🇮",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "386",
    phoneMask: "##-###-####",
  },
  {
    name: "Solomon Islands",
    officialName: "Solomon Islands",
    alpha2: "SB",
    alpha3: "SLB",
    numeric: "090",
    capital: "Honiara",
    region: "Oceania",
    subregion: "Melanesia",
    continent: "Oceania",
    nativeName: "Solomon Islands",
    languages: ["English"],
    flag: "🇸🇧",
    currency: {
      code: "SBD",
      name: "Solomon Islands dollar",
      symbol: "$",
    },
    phoneCode: "677",
    phoneMask: "######",
  },
  {
    name: "Somalia",
    officialName: "Federal Republic of Somalia",
    alpha2: "SO",
    alpha3: "SOM",
    numeric: "706",
    capital: "Mogadishu",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Soomaaliya",
    languages: ["Somali", "Arabic"],
    flag: "🇸🇴",
    currency: {
      code: "SOS",
      name: "Somali shilling",
      symbol: "Sh",
    },
    phoneCode: "252",
    phoneMask: "##-###-####",
  },
  {
    name: "South Korea",
    officialName: "Republic of Korea",
    alpha2: "KR",
    alpha3: "KOR",
    numeric: "410",
    capital: "Seoul",
    region: "Asia",
    subregion: "Eastern Asia",
    continent: "Asia",
    nativeName: "대한민국",
    languages: ["Korean"],
    flag: "🇰🇷",
    currency: {
      code: "KRW",
      name: "South Korean won",
      symbol: "₩",
    },
    phoneCode: "82",
    phoneMask: "##-###-#####",
  },
  {
    name: "South Sudan",
    officialName: "Republic of South Sudan",
    alpha2: "SS",
    alpha3: "SSD",
    numeric: "728",
    capital: "Juba",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "South Sudan",
    languages: ["English"],
    flag: "🇸🇸",
    currency: {
      code: "SSP",
      name: "South Sudanese pound",
      symbol: "£",
    },
    phoneCode: "211",
    phoneMask: "###-###-####",
  },
  {
    name: "Spain",
    officialName: "Kingdom of Spain",
    alpha2: "ES",
    alpha3: "ESP",
    numeric: "724",
    capital: "Madrid",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "España",
    languages: ["Spanish"],
    flag: "🇪🇸",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    phoneCode: "34",
    phoneMask: "###-###-####",
  },
  {
    name: "Sri Lanka",
    officialName: "Democratic Socialist Republic of Sri Lanka",
    alpha2: "LK",
    alpha3: "LKA",
    numeric: "144",
    capital: "Colombo",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "ශ්‍රී ලංකා",
    languages: ["Sinhala", "Tamil"],
    flag: "🇱🇰",
    currency: {
      code: "LKR",
      name: "Sri Lankan rupee",
      symbol: "₨",
    },
    phoneCode: "94",
    phoneMask: "##-###-#####",
  },
  {
    name: "Sudan",
    officialName: "Republic of the Sudan",
    alpha2: "SD",
    alpha3: "SDN",
    numeric: "729",
    capital: "Khartoum",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "السودان",
    languages: ["Arabic", "English"],
    flag: "🇸🇩",
    currency: {
      code: "SDG",
      name: "Sudanese pound",
      symbol: "£",
    },
    phoneCode: "249",
    phoneMask: "##-###-#####",
  },
  {
    name: "Suriname",
    officialName: "Republic of Suriname",
    alpha2: "SR",
    alpha3: "SUR",
    numeric: "740",
    capital: "Paramaribo",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Suriname",
    languages: ["Dutch"],
    flag: "🇸🇷",
    currency: {
      code: "SRD",
      name: "Surinamese dollar",
      symbol: "$",
    },
    phoneCode: "597",
    phoneMask: "###-#####",
  },
  {
    name: "Sweden",
    officialName: "Kingdom of Sweden",
    alpha2: "SE",
    alpha3: "SWE",
    numeric: "752",
    capital: "Stockholm",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Sverige",
    languages: ["Swedish"],
    flag: "🇸🇪",
    currency: {
      code: "SEK",
      name: "Swedish krona",
      symbol: "kr",
    },
    phoneCode: "46",
    phoneMask: "##-###-#####",
  },
  {
    name: "Switzerland",
    officialName: "Swiss Confederation",
    alpha2: "CH",
    alpha3: "CHE",
    numeric: "756",
    capital: "Bern",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Schweiz",
    languages: ["German", "French", "Italian", "Romansh"],
    flag: "🇨🇭",
    currency: {
      code: "CHF",
      name: "Swiss franc",
      symbol: "CHF",
    },
    phoneCode: "41",
    phoneMask: "##-###-#####",
  },
  {
    name: "Syria",
    officialName: "Syrian Arab Republic",
    alpha2: "SY",
    alpha3: "SYR",
    numeric: "760",
    capital: "Damascus",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "سوريا",
    languages: ["Arabic"],
    flag: "🇸🇾",
    currency: {
      code: "SYP",
      name: "Syrian pound",
      symbol: "£",
    },
    phoneCode: "963",
    phoneMask: "###-###-####",
  },
  {
    name: "Tajikistan",
    officialName: "Republic of Tajikistan",
    alpha2: "TJ",
    alpha3: "TJK",
    numeric: "762",
    capital: "Dushanbe",
    region: "Asia",
    subregion: "Central Asia",
    continent: "Asia",
    nativeName: "Тоҷикистон",
    languages: ["Tajik"],
    flag: "🇹🇯",
    currency: {
      code: "TJS",
      name: "Tajikistani somoni",
      symbol: "SM",
    },
    phoneCode: "992",
    phoneMask: "###-###-####",
  },
  {
    name: "Tanzania",
    officialName: "United Republic of Tanzania",
    alpha2: "TZ",
    alpha3: "TZA",
    numeric: "834",
    capital: "Dodoma",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Tanzania",
    languages: ["Swahili", "English"],
    flag: "🇹🇿",
    currency: {
      code: "TZS",
      name: "Tanzanian shilling",
      symbol: "TSh",
    },
    phoneCode: "255",
    phoneMask: "###-###-####",
  },
  {
    name: "Thailand",
    officialName: "Kingdom of Thailand",
    alpha2: "TH",
    alpha3: "THA",
    numeric: "764",
    capital: "Bangkok",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "ประเทศไทย",
    languages: ["Thai"],
    flag: "🇹🇭",
    currency: {
      code: "THB",
      name: "Thai baht",
      symbol: "฿",
    },
    phoneCode: "66",
    phoneMask: "##-###-#####",
  },
  {
    name: "Togo",
    officialName: "Togolese Republic",
    alpha2: "TG",
    alpha3: "TGO",
    numeric: "768",
    capital: "Lomé",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Togo",
    languages: ["French"],
    flag: "🇹🇬",
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "228",
    phoneMask: "##-###-####",
  },
  {
    name: "Tonga",
    officialName: "Kingdom of Tonga",
    alpha2: "TO",
    alpha3: "TON",
    numeric: "776",
    capital: "Nukuʻalofa",
    region: "Oceania",
    subregion: "Polynesia",
    continent: "Oceania",
    nativeName: "Tonga",
    languages: ["Tongan", "English"],
    flag: "🇹🇴",
    currency: {
      code: "TOP",
      name: "Tongan paʻanga",
      symbol: "T$",
    },
    phoneCode: "676",
    phoneMask: "######",
  },
  {
    name: "Trinidad and Tobago",
    officialName: "Republic of Trinidad and Tobago",
    alpha2: "TT",
    alpha3: "TTO",
    numeric: "780",
    capital: "Port of Spain",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Trinidad and Tobago",
    languages: ["English"],
    flag: "🇹🇹",
    currency: {
      code: "TTD",
      name: "Trinidad and Tobago dollar",
      symbol: "$",
    },
    phoneCode: "1-868",
    phoneMask: "+1-868-###-#####",
  },
  {
    name: "Tunisia",
    officialName: "Republic of Tunisia",
    alpha2: "TN",
    alpha3: "TUN",
    numeric: "788",
    capital: "Tunis",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "تونس",
    languages: ["Arabic"],
    flag: "🇹🇳",
    currency: {
      code: "TND",
      name: "Tunisian dinar",
      symbol: "د.ت",
    },
    phoneCode: "216",
    phoneMask: "##-###-####",
  },
  {
    name: "Turkey",
    officialName: "Republic of Türkiye",
    alpha2: "TR",
    alpha3: "TUR",
    numeric: "792",
    capital: "Ankara",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "Türkiye",
    languages: ["Turkish"],
    flag: "🇹🇷",
    currency: {
      code: "TRY",
      name: "Turkish lira",
      symbol: "₺",
    },
    phoneCode: "90",
    phoneMask: "###-###-#####",
  },
  {
    name: "Turkmenistan",
    officialName: "Turkmenistan",
    alpha2: "TM",
    alpha3: "TKM",
    numeric: "795",
    capital: "Ashgabat",
    region: "Asia",
    subregion: "Central Asia",
    continent: "Asia",
    nativeName: "Türkmenistan",
    languages: ["Turkmen"],
    flag: "🇹🇲",
    currency: {
      code: "TMT",
      name: "Turkmenistan manat",
      symbol: "m",
    },
    phoneCode: "993",
    phoneMask: "##-###-####",
  },
  {
    name: "Tuvalu",
    officialName: "Tuvalu",
    alpha2: "TV",
    alpha3: "TUV",
    numeric: "798",
    capital: "Funafuti",
    region: "Oceania",
    subregion: "Polynesia",
    continent: "Oceania",
    nativeName: "Tuvalu",
    languages: ["English", "Tuvaluan"],
    flag: "🇹🇻",
    currency: {
      code: "AUD",
      name: "Australian dollar",
      symbol: "$",
    },
    phoneCode: "688",
    phoneMask: "######",
  },
  {
    name: "Uganda",
    officialName: "Republic of Uganda",
    alpha2: "UG",
    alpha3: "UGA",
    numeric: "800",
    capital: "Kampala",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Uganda",
    languages: ["English", "Swahili"],
    flag: "🇺🇬",
    currency: {
      code: "UGX",
      name: "Ugandan shilling",
      symbol: "USh",
    },
    phoneCode: "256",
    phoneMask: "###-###-####",
  },
  {
    name: "Ukraine",
    officialName: "Ukraine",
    alpha2: "UA",
    alpha3: "UKR",
    numeric: "804",
    capital: "Kyiv",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Україна",
    languages: ["Ukrainian"],
    flag: "🇺🇦",
    currency: {
      code: "UAH",
      name: "Ukrainian hryvnia",
      symbol: "₴",
    },
    phoneCode: "380",
    phoneMask: "##-###-#####",
  },
  {
    name: "United Arab Emirates",
    officialName: "United Arab Emirates",
    alpha2: "AE",
    alpha3: "ARE",
    numeric: "784",
    capital: "Abu Dhabi",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "الإمارات العربية المتحدة",
    languages: ["Arabic"],
    flag: "🇦🇪",
    currency: {
      code: "AED",
      name: "United Arab Emirates dirham",
      symbol: "د.إ",
    },
    phoneCode: "971",
    phoneMask: "##-###-#####",
  },
  {
    name: "Uruguay",
    officialName: "Oriental Republic of Uruguay",
    alpha2: "UY",
    alpha3: "URY",
    numeric: "858",
    capital: "Montevideo",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Uruguay",
    languages: ["Spanish"],
    flag: "🇺🇾",
    currency: {
      code: "UYU",
      name: "Uruguayan peso",
      symbol: "$",
    },
    phoneCode: "598",
    phoneMask: "##-###-####",
  },
  {
    name: "Uzbekistan",
    officialName: "Republic of Uzbekistan",
    alpha2: "UZ",
    alpha3: "UZB",
    numeric: "860",
    capital: "Tashkent",
    region: "Asia",
    subregion: "Central Asia",
    continent: "Asia",
    nativeName: "Oʻzbekiston",
    languages: ["Uzbek"],
    flag: "🇺🇿",
    currency: {
      code: "UZS",
      name: "Uzbekistani soʻm",
      symbol: "soʻm",
    },
    phoneCode: "998",
    phoneMask: "##-###-#####",
  },
  {
    name: "Vanuatu",
    officialName: "Republic of Vanuatu",
    alpha2: "VU",
    alpha3: "VUT",
    numeric: "548",
    capital: "Port Vila",
    region: "Oceania",
    subregion: "Melanesia",
    continent: "Oceania",
    nativeName: "Vanuatu",
    languages: ["Bislama", "English", "French"],
    flag: "🇻🇺",
    currency: {
      code: "VUV",
      name: "Vanuatu vatu",
      symbol: "Vt",
    },
    phoneCode: "678",
    phoneMask: "######",
  },
  {
    name: "Venezuela",
    officialName: "Bolivarian Republic of Venezuela",
    alpha2: "VE",
    alpha3: "VEN",
    numeric: "862",
    capital: "Caracas",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Venezuela",
    languages: ["Spanish"],
    flag: "🇻🇪",
    currency: {
      code: "VES",
      name: "Venezuelan bolívar",
      symbol: "Bs.",
    },
    phoneCode: "58",
    phoneMask: "###-###-#####",
  },
  {
    name: "Vietnam",
    officialName: "Socialist Republic of Vietnam",
    alpha2: "VN",
    alpha3: "VNM",
    numeric: "704",
    capital: "Hanoi",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Việt Nam",
    languages: ["Vietnamese"],
    flag: "🇻🇳",
    currency: {
      code: "VND",
      name: "Vietnamese đồng",
      symbol: "₫",
    },
    phoneCode: "84",
    phoneMask: "###-###-####",
  },
  {
    name: "Yemen",
    officialName: "Republic of Yemen",
    alpha2: "YE",
    alpha3: "YEM",
    numeric: "887",
    capital: "Sana'a",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "اليمن",
    languages: ["Arabic"],
    flag: "🇾🇪",
    currency: {
      code: "YER",
      name: "Yemeni rial",
      symbol: "﷼",
    },
    phoneCode: "967",
    phoneMask: "###-###-####",
  },
  {
    name: "Zambia",
    officialName: "Republic of Zambia",
    alpha2: "ZM",
    alpha3: "ZMB",
    numeric: "894",
    capital: "Lusaka",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Zambia",
    languages: ["English"],
    flag: "🇿🇲",
    currency: {
      code: "ZMW",
      name: "Zambian kwacha",
      symbol: "ZK",
    },
    phoneCode: "260",
    phoneMask: "##-###-#####",
  },
  {
    name: "Zimbabwe",
    officialName: "Republic of Zimbabwe",
    alpha2: "ZW",
    alpha3: "ZWE",
    numeric: "716",
    capital: "Harare",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Zimbabwe",
    languages: ["English", "Shona", "Ndebele"],
    flag: "🇿🇼",
    currency: {
      code: "ZWL",
      name: "Zimbabwean dollar",
      symbol: "$",
    },
    phoneCode: "263",
    phoneMask: "##-###-#####",
  },
  {
    name: "Timor-Leste",
    officialName: "Democratic Republic of Timor-Leste",
    alpha2: "TL",
    alpha3: "TLS",
    numeric: "626",
    capital: "Dili",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Timor-Leste",
    languages: ["Portuguese", "Tetum"],
    flag: "🇹🇱",
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "670",
    phoneMask: "###-#####",
  },
] as const;
