export const countries = [
  {
    name: "United States",
    officialName: "United States of America",
    alpha2: "US",
    alpha3: "USA",
    numeric: "840",
    capital: "Washington, D.C.",
    region: "Americas",
    subregion: "Northern America",
    continent: "North America",
    nativeName: "United States",
    languages: ["English"],
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "+1",
    phoneMask: "+1 (###) ###-####",
  },
  {
    name: "Canada",
    officialName: "Canada",
    alpha2: "CA",
    alpha3: "CAN",
    numeric: "124",
    capital: "Ottawa",
    region: "Americas",
    subregion: "Northern America",
    continent: "North America",
    nativeName: "Canada",
    languages: ["English", "French"],
    currency: { code: "CAD", name: "Canadian dollar", symbol: "$" },
    phoneCode: "+1",
    phoneMask: "+1 (###) ###-####",
  },
  {
    name: "Brazil",
    officialName: "Federative Republic of Brazil",
    alpha2: "BR",
    alpha3: "BRA",
    numeric: "076",
    capital: "Brasília",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Brasil",
    languages: ["Portuguese"],
    currency: { code: "BRL", name: "Brazilian real", symbol: "R$" },
    phoneCode: "+55",
    phoneMask: "+55 (##) #####-####",
  },
  {
    name: "United Kingdom",
    officialName: "United Kingdom of Great Britain and Northern Ireland",
    alpha2: "GB",
    alpha3: "GBR",
    numeric: "826",
    capital: "London",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "United Kingdom",
    languages: ["English"],
    currency: { code: "GBP", name: "British pound", symbol: "£" },
    phoneCode: "+44",
    phoneMask: "+44 #### ######",
  },
  {
    name: "Germany",
    officialName: "Federal Republic of Germany",
    alpha2: "DE",
    alpha3: "DEU",
    numeric: "276",
    capital: "Berlin",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Deutschland",
    languages: ["German"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+49",
    phoneMask: "+49 ### #######",
  },
  {
    name: "France",
    officialName: "French Republic",
    alpha2: "FR",
    alpha3: "FRA",
    numeric: "250",
    capital: "Paris",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "France",
    languages: ["French"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+33",
    phoneMask: "+33 # ## ## ## ##",
  },
  {
    name: "China",
    officialName: "People's Republic of China",
    alpha2: "CN",
    alpha3: "CHN",
    numeric: "156",
    capital: "Beijing",
    region: "Asia",
    subregion: "Eastern Asia",
    continent: "Asia",
    nativeName: "中国",
    languages: ["Chinese"],
    currency: { code: "CNY", name: "Chinese yuan", symbol: "¥" },
    phoneCode: "+86",
    phoneMask: "+86 ### #### ####",
  },
  {
    name: "Japan",
    officialName: "Japan",
    alpha2: "JP",
    alpha3: "JPN",
    numeric: "392",
    capital: "Tokyo",
    region: "Asia",
    subregion: "Eastern Asia",
    continent: "Asia",
    nativeName: "日本",
    languages: ["Japanese"],
    currency: { code: "JPY", name: "Japanese yen", symbol: "¥" },
    phoneCode: "+81",
    phoneMask: "+81 ## #### ####",
  },
  {
    name: "India",
    officialName: "Republic of India",
    alpha2: "IN",
    alpha3: "IND",
    numeric: "356",
    capital: "New Delhi",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "भारत",
    languages: ["Hindi", "English"],
    currency: { code: "INR", name: "Indian rupee", symbol: "₹" },
    phoneCode: "+91",
    phoneMask: "+91 ##### #####",
  },
  {
    name: "Australia",
    officialName: "Commonwealth of Australia",
    alpha2: "AU",
    alpha3: "AUS",
    numeric: "036",
    capital: "Canberra",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    continent: "Oceania",
    nativeName: "Australia",
    languages: ["English"],
    currency: { code: "AUD", name: "Australian dollar", symbol: "$" },
    phoneCode: "+61",
    phoneMask: "+61 # #### ####",
  },
  {
    name: "South Africa",
    officialName: "Republic of South Africa",
    alpha2: "ZA",
    alpha3: "ZAF",
    numeric: "710",
    capital: "Pretoria",
    region: "Africa",
    subregion: "Southern Africa",
    continent: "Africa",
    nativeName: "Afrika Borwa",
    languages: [
      "Afrikaans",
      "English",
      "Zulu",
      "Xhosa",
      "Swati",
      "Tswana",
      "Southern Sotho",
      "Venda",
      "Tsonga",
      "Northern Sotho",
      "Ndebele",
    ],
    currency: { code: "ZAR", name: "South African rand", symbol: "R" },
    phoneCode: "+27",
    phoneMask: "+27 ## ### ####",
  },
  {
    name: "Nigeria",
    officialName: "Federal Republic of Nigeria",
    alpha2: "NG",
    alpha3: "NGA",
    numeric: "566",
    capital: "Abuja",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Nigeria",
    languages: ["English"],
    currency: { code: "NGN", name: "Nigerian naira", symbol: "₦" },
    phoneCode: "+234",
    phoneMask: "+234 ### ### ####",
  },
  {
    name: "Mexico",
    officialName: "United Mexican States",
    alpha2: "MX",
    alpha3: "MEX",
    numeric: "484",
    capital: "Mexico City",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "México",
    languages: ["Spanish"],
    currency: { code: "MXN", name: "Mexican peso", symbol: "$" },
    phoneCode: "+52",
    phoneMask: "+52 ### ### ####",
  },
  {
    name: "Russia",
    officialName: "Russian Federation",
    alpha2: "RU",
    alpha3: "RUS",
    numeric: "643",
    capital: "Moscow",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Россия",
    languages: ["Russian"],
    currency: { code: "RUB", name: "Russian ruble", symbol: "₽" },
    phoneCode: "+7",
    phoneMask: "+7 ### ### ####",
  },
  {
    name: "Saudi Arabia",
    officialName: "Kingdom of Saudi Arabia",
    alpha2: "SA",
    alpha3: "SAU",
    numeric: "682",
    capital: "Riyadh",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "المملكة العربية السعودية",
    languages: ["Arabic"],
    currency: { code: "SAR", name: "Saudi riyal", symbol: "ر.س" },
    phoneCode: "+966",
    phoneMask: "+966 # #### ####",
  },
  {
    name: "Afghanistan",
    officialName: "Islamic Republic of Afghanistan",
    alpha2: "AF",
    alpha3: "AFG",
    numeric: "004",
    capital: "Kabul",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "افغانستان",
    languages: ["Pashto", "Dari"],
    currency: { code: "AFN", name: "Afghan afghani", symbol: "؋" },
    phoneCode: "+93",
    phoneMask: "+93 ## ### ####",
  },
  {
    name: "Albania",
    officialName: "Republic of Albania",
    alpha2: "AL",
    alpha3: "ALB",
    numeric: "008",
    capital: "Tirana",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Shqipëria",
    languages: ["Albanian"],
    currency: { code: "ALL", name: "Albanian lek", symbol: "L" },
    phoneCode: "+355",
    phoneMask: "+355 ## ### ####",
  },
  {
    name: "Algeria",
    officialName: "People's Democratic Republic of Algeria",
    alpha2: "DZ",
    alpha3: "DZA",
    numeric: "012",
    capital: "Algiers",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "الجزائر",
    languages: ["Arabic"],
    currency: { code: "DZD", name: "Algerian dinar", symbol: "د.ج" },
    phoneCode: "+213",
    phoneMask: "+213 ## ### ####",
  },
  {
    name: "Andorra",
    officialName: "Principality of Andorra",
    alpha2: "AD",
    alpha3: "AND",
    numeric: "020",
    capital: "Andorra la Vella",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Andorra",
    languages: ["Catalan"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+376",
    phoneMask: "+376 ### ###",
  },
  {
    name: "Angola",
    officialName: "Republic of Angola",
    alpha2: "AO",
    alpha3: "AGO",
    numeric: "024",
    capital: "Luanda",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Angola",
    languages: ["Portuguese"],
    currency: { code: "AOA", name: "Angolan kwanza", symbol: "Kz" },
    phoneCode: "+244",
    phoneMask: "+244 ### ### ###",
  },
  {
    name: "Antigua and Barbuda",
    officialName: "Antigua and Barbuda",
    alpha2: "AG",
    alpha3: "ATG",
    numeric: "028",
    capital: "Saint John's",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Antigua and Barbuda",
    languages: ["English"],
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "+1-268",
    phoneMask: "+1 (268) ###-####",
  },
  {
    name: "Argentina",
    officialName: "Argentine Republic",
    alpha2: "AR",
    alpha3: "ARG",
    numeric: "032",
    capital: "Buenos Aires",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Argentina",
    languages: ["Spanish"],
    currency: { code: "ARS", name: "Argentine peso", symbol: "$" },
    phoneCode: "+54",
    phoneMask: "+54 ### ### ####",
  },
  {
    name: "Armenia",
    officialName: "Republic of Armenia",
    alpha2: "AM",
    alpha3: "ARM",
    numeric: "051",
    capital: "Yerevan",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "Հայաստան",
    languages: ["Armenian"],
    currency: { code: "AMD", name: "Armenian dram", symbol: "֏" },
    phoneCode: "+374",
    phoneMask: "+374 ## ### ###",
  },
  {
    name: "Austria",
    officialName: "Republic of Austria",
    alpha2: "AT",
    alpha3: "AUT",
    numeric: "040",
    capital: "Vienna",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Österreich",
    languages: ["German"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+43",
    phoneMask: "+43 ### ### ###",
  },
  {
    name: "Azerbaijan",
    officialName: "Republic of Azerbaijan",
    alpha2: "AZ",
    alpha3: "AZE",
    numeric: "031",
    capital: "Baku",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "Azərbaycan",
    languages: ["Azerbaijani"],
    currency: { code: "AZN", name: "Azerbaijani manat", symbol: "₼" },
    phoneCode: "+994",
    phoneMask: "+994 ## ### ####",
  },
  {
    name: "Bahamas",
    officialName: "Commonwealth of The Bahamas",
    alpha2: "BS",
    alpha3: "BHS",
    numeric: "044",
    capital: "Nassau",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Bahamas",
    languages: ["English"],
    currency: { code: "BSD", name: "Bahamian dollar", symbol: "$" },
    phoneCode: "+1-242",
    phoneMask: "+1 (242) ###-####",
  },
  {
    name: "Bahrain",
    officialName: "Kingdom of Bahrain",
    alpha2: "BH",
    alpha3: "BHR",
    numeric: "048",
    capital: "Manama",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "البحرين",
    languages: ["Arabic"],
    currency: { code: "BHD", name: "Bahraini dinar", symbol: ".د.ب" },
    phoneCode: "+973",
    phoneMask: "+973 #### ####",
  },
  {
    name: "Bangladesh",
    officialName: "People's Republic of Bangladesh",
    alpha2: "BD",
    alpha3: "BGD",
    numeric: "050",
    capital: "Dhaka",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "বাংলাদেশ",
    languages: ["Bengali"],
    currency: { code: "BDT", name: "Bangladeshi taka", symbol: "৳" },
    phoneCode: "+880",
    phoneMask: "+880 #### ######",
  },
  {
    name: "Barbados",
    officialName: "Barbados",
    alpha2: "BB",
    alpha3: "BRB",
    numeric: "052",
    capital: "Bridgetown",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Barbados",
    languages: ["English"],
    currency: { code: "BBD", name: "Barbadian dollar", symbol: "$" },
    phoneCode: "+1-246",
    phoneMask: "+1 (246) ###-####",
  },
  {
    name: "Belarus",
    officialName: "Republic of Belarus",
    alpha2: "BY",
    alpha3: "BLR",
    numeric: "112",
    capital: "Minsk",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Беларусь",
    languages: ["Belarusian", "Russian"],
    currency: { code: "BYN", name: "Belarusian ruble", symbol: "Br" },
    phoneCode: "+375",
    phoneMask: "+375 ## ### ####",
  },
  {
    name: "Belgium",
    officialName: "Kingdom of Belgium",
    alpha2: "BE",
    alpha3: "BEL",
    numeric: "056",
    capital: "Brussels",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "België",
    languages: ["Dutch", "French", "German"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+32",
    phoneMask: "+32 ### ### ###",
  },
  {
    name: "Belize",
    officialName: "Belize",
    alpha2: "BZ",
    alpha3: "BLZ",
    numeric: "084",
    capital: "Belmopan",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Belize",
    languages: ["English"],
    currency: { code: "BZD", name: "Belize dollar", symbol: "$" },
    phoneCode: "+501",
    phoneMask: "+501 ### ####",
  },
  {
    name: "Benin",
    officialName: "Republic of Benin",
    alpha2: "BJ",
    alpha3: "BEN",
    numeric: "204",
    capital: "Porto-Novo",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Bénin",
    languages: ["French"],
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+229",
    phoneMask: "+229 ## ### ###",
  },
  {
    name: "Bhutan",
    officialName: "Kingdom of Bhutan",
    alpha2: "BT",
    alpha3: "BTN",
    numeric: "064",
    capital: "Thimphu",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "འབྲུག",
    languages: ["Dzongkha"],
    currency: {
      code: "BTN",
      name: "Bhutanese ngultrum",
      symbol: "Nu.",
    },
    phoneCode: "+975",
    phoneMask: "+975 # ### ####",
  },
  {
    name: "Bolivia",
    officialName: "Plurinational State of Bolivia",
    alpha2: "BO",
    alpha3: "BOL",
    numeric: "068",
    capital: "Sucre",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Bolivia",
    languages: ["Spanish", "Quechua", "Aymara"],
    currency: {
      code: "BOB",
      name: "Bolivian boliviano",
      symbol: "Bs.",
    },
    phoneCode: "+591",
    phoneMask: "+591 # ### ####",
  },
  {
    name: "Bosnia and Herzegovina",
    officialName: "Bosnia and Herzegovina",
    alpha2: "BA",
    alpha3: "BIH",
    numeric: "070",
    capital: "Sarajevo",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Bosna i Hercegovina",
    languages: ["Bosnian", "Croatian", "Serbian"],
    currency: {
      code: "BAM",
      name: "Bosnia and Herzegovina convertible mark",
      symbol: "KM",
    },
    phoneCode: "+387",
    phoneMask: "+387 ## ### ###",
  },
  {
    name: "Botswana",
    officialName: "Republic of Botswana",
    alpha2: "BW",
    alpha3: "BWA",
    numeric: "072",
    capital: "Gaborone",
    region: "Africa",
    subregion: "Southern Africa",
    continent: "Africa",
    nativeName: "Botswana",
    languages: ["English", "Tswana"],
    currency: { code: "BWP", name: "Botswana pula", symbol: "P" },
    phoneCode: "+267",
    phoneMask: "+267 ## ### ###",
  },
  {
    name: "Brunei",
    officialName: "Nation of Brunei, the Abode of Peace",
    alpha2: "BN",
    alpha3: "BRN",
    numeric: "096",
    capital: "Bandar Seri Begawan",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Brunei",
    languages: ["Malay"],
    currency: { code: "BND", name: "Brunei dollar", symbol: "$" },
    phoneCode: "+673",
    phoneMask: "+673 ### ####",
  },
  {
    name: "Bulgaria",
    officialName: "Republic of Bulgaria",
    alpha2: "BG",
    alpha3: "BGR",
    numeric: "100",
    capital: "Sofia",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "България",
    languages: ["Bulgarian"],
    currency: { code: "BGN", name: "Bulgarian lev", symbol: "лв" },
    phoneCode: "+359",
    phoneMask: "+359 ### ### ###",
  },
  {
    name: "Burkina Faso",
    officialName: "Burkina Faso",
    alpha2: "BF",
    alpha3: "BFA",
    numeric: "854",
    capital: "Ouagadougou",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Burkina Faso",
    languages: ["French"],
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+226",
    phoneMask: "+226 ## ### ###",
  },
  {
    name: "Burundi",
    officialName: "Republic of Burundi",
    alpha2: "BI",
    alpha3: "BDI",
    numeric: "108",
    capital: "Gitega",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Uburundi",
    languages: ["Kirundi", "French", "English"],
    currency: { code: "BIF", name: "Burundian franc", symbol: "FBu" },
    phoneCode: "+257",
    phoneMask: "+257 ## ### ###",
  },
  {
    name: "Cabo Verde",
    officialName: "Republic of Cabo Verde",
    alpha2: "CV",
    alpha3: "CPV",
    numeric: "132",
    capital: "Praia",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Cabo Verde",
    languages: ["Portuguese"],
    currency: { code: "CVE", name: "Cape Verdean escudo", symbol: "$" },
    phoneCode: "+238",
    phoneMask: "+238 ### ####",
  },
  {
    name: "Cambodia",
    officialName: "Kingdom of Cambodia",
    alpha2: "KH",
    alpha3: "KHM",
    numeric: "116",
    capital: "Phnom Penh",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "កម្ពុជា",
    languages: ["Khmer"],
    currency: { code: "KHR", name: "Cambodian riel", symbol: "៛" },
    phoneCode: "+855",
    phoneMask: "+855 ## ### ###",
  },
  {
    name: "Cameroon",
    officialName: "Republic of Cameroon",
    alpha2: "CM",
    alpha3: "CMR",
    numeric: "120",
    capital: "Yaoundé",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Cameroun",
    languages: ["English", "French"],
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+237",
    phoneMask: "+237 ### ### ###",
  },
  {
    name: "Central African Republic",
    officialName: "Central African Republic",
    alpha2: "CF",
    alpha3: "CAF",
    numeric: "140",
    capital: "Bangui",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "République centrafricaine",
    languages: ["French", "Sango"],
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+236",
    phoneMask: "+236 ## ### ###",
  },
  {
    name: "Chad",
    officialName: "Republic of Chad",
    alpha2: "TD",
    alpha3: "TCD",
    numeric: "148",
    capital: "N'Djamena",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Tchad",
    languages: ["French", "Arabic"],
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+235",
    phoneMask: "+235 ## ### ###",
  },
  {
    name: "Chile",
    officialName: "Republic of Chile",
    alpha2: "CL",
    alpha3: "CHL",
    numeric: "152",
    capital: "Santiago",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Chile",
    languages: ["Spanish"],
    currency: { code: "CLP", name: "Chilean peso", symbol: "$" },
    phoneCode: "+56",
    phoneMask: "+56 # #### ####",
  },
  {
    name: "Colombia",
    officialName: "Republic of Colombia",
    alpha2: "CO",
    alpha3: "COL",
    numeric: "170",
    capital: "Bogotá",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Colombia",
    languages: ["Spanish"],
    currency: { code: "COP", name: "Colombian peso", symbol: "$" },
    phoneCode: "+57",
    phoneMask: "+57 ### ### ####",
  },
  {
    name: "Comoros",
    officialName: "Union of the Comoros",
    alpha2: "KM",
    alpha3: "COM",
    numeric: "174",
    capital: "Moroni",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "جزر القمر",
    languages: ["Arabic", "French", "Comorian"],
    currency: { code: "KMF", name: "Comorian franc", symbol: "CF" },
    phoneCode: "+269",
    phoneMask: "+269 ### ####",
  },
  {
    name: "Congo (Congo-Brazzaville)",
    officialName: "Republic of the Congo",
    alpha2: "CG",
    alpha3: "COG",
    numeric: "178",
    capital: "Brazzaville",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Congo",
    languages: ["French"],
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+242",
    phoneMask: "+242 ## ### ####",
  },
  {
    name: "Congo (Congo-Kinshasa)",
    officialName: "Democratic Republic of the Congo",
    alpha2: "CD",
    alpha3: "COD",
    numeric: "180",
    capital: "Kinshasa",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "République démocratique du Congo",
    languages: ["French"],
    currency: { code: "CDF", name: "Congolese franc", symbol: "FC" },
    phoneCode: "+243",
    phoneMask: "+243 ## ### ####",
  },
  {
    name: "Costa Rica",
    officialName: "Republic of Costa Rica",
    alpha2: "CR",
    alpha3: "CRI",
    numeric: "188",
    capital: "San José",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Costa Rica",
    languages: ["Spanish"],
    currency: { code: "CRC", name: "Costa Rican colón", symbol: "₡" },
    phoneCode: "+506",
    phoneMask: "+506 #### ####",
  },
  {
    name: "Croatia",
    officialName: "Republic of Croatia",
    alpha2: "HR",
    alpha3: "HRV",
    numeric: "191",
    capital: "Zagreb",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Hrvatska",
    languages: ["Croatian"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+385",
    phoneMask: "+385 ## ### ####",
  },
  {
    name: "Cuba",
    officialName: "Republic of Cuba",
    alpha2: "CU",
    alpha3: "CUB",
    numeric: "192",
    capital: "Havana",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Cuba",
    languages: ["Spanish"],
    currency: { code: "CUP", name: "Cuban peso", symbol: "$" },
    phoneCode: "+53",
    phoneMask: "+53 # ### ####",
  },
  {
    name: "Cyprus",
    officialName: "Republic of Cyprus",
    alpha2: "CY",
    alpha3: "CYP",
    numeric: "196",
    capital: "Nicosia",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "Κύπρος",
    languages: ["Greek", "Turkish"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+357",
    phoneMask: "+357 ## ### ###",
  },
  {
    name: "Czech Republic",
    officialName: "Czech Republic",
    alpha2: "CZ",
    alpha3: "CZE",
    numeric: "203",
    capital: "Prague",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Česko",
    languages: ["Czech"],
    currency: { code: "CZK", name: "Czech koruna", symbol: "Kč" },
    phoneCode: "+420",
    phoneMask: "+420 ### ### ###",
  },
  {
    name: "Denmark",
    officialName: "Kingdom of Denmark",
    alpha2: "DK",
    alpha3: "DNK",
    numeric: "208",
    capital: "Copenhagen",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Danmark",
    languages: ["Danish"],
    currency: { code: "DKK", name: "Danish krone", symbol: "kr" },
    phoneCode: "+45",
    phoneMask: "+45 ## ## ## ##",
  },
  {
    name: "Djibouti",
    officialName: "Republic of Djibouti",
    alpha2: "DJ",
    alpha3: "DJI",
    numeric: "262",
    capital: "Djibouti",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "جيبوتي",
    languages: ["French", "Arabic"],
    currency: { code: "DJF", name: "Djiboutian franc", symbol: "Fdj" },
    phoneCode: "+253",
    phoneMask: "+253 ## ### ###",
  },
  {
    name: "Dominica",
    officialName: "Commonwealth of Dominica",
    alpha2: "DM",
    alpha3: "DMA",
    numeric: "212",
    capital: "Roseau",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Dominica",
    languages: ["English"],
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "+1-767",
    phoneMask: "+1 (767) ###-####",
  },
  {
    name: "Dominican Republic",
    officialName: "Dominican Republic",
    alpha2: "DO",
    alpha3: "DOM",
    numeric: "214",
    capital: "Santo Domingo",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "República Dominicana",
    languages: ["Spanish"],
    currency: { code: "DOP", name: "Dominican peso", symbol: "$" },
    phoneCode: "+1-809",
    phoneMask: "+1 (809) ###-####",
  },
  {
    name: "Ecuador",
    officialName: "Republic of Ecuador",
    alpha2: "EC",
    alpha3: "ECU",
    numeric: "218",
    capital: "Quito",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Ecuador",
    languages: ["Spanish"],
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "+593",
    phoneMask: "+593 ## ### ####",
  },
  {
    name: "Egypt",
    officialName: "Arab Republic of Egypt",
    alpha2: "EG",
    alpha3: "EGY",
    numeric: "818",
    capital: "Cairo",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "مصر",
    languages: ["Arabic"],
    currency: { code: "EGP", name: "Egyptian pound", symbol: "£" },
    phoneCode: "+20",
    phoneMask: "+20 ### ### ####",
  },
  {
    name: "El Salvador",
    officialName: "Republic of El Salvador",
    alpha2: "SV",
    alpha3: "SLV",
    numeric: "222",
    capital: "San Salvador",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "El Salvador",
    languages: ["Spanish"],
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "+503",
    phoneMask: "+503 #### ####",
  },
  {
    name: "Equatorial Guinea",
    officialName: "Republic of Equatorial Guinea",
    alpha2: "GQ",
    alpha3: "GNQ",
    numeric: "226",
    capital: "Malabo",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Guinea Ecuatorial",
    languages: ["Spanish", "French", "Portuguese"],
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+240",
    phoneMask: "+240 ### ### ###",
  },
  {
    name: "Eritrea",
    officialName: "State of Eritrea",
    alpha2: "ER",
    alpha3: "ERI",
    numeric: "232",
    capital: "Asmara",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "ኤርትራ",
    languages: ["Tigrinya", "Arabic", "English"],
    currency: { code: "ERN", name: "Eritrean nakfa", symbol: "Nfk" },
    phoneCode: "+291",
    phoneMask: "+291 # ### ###",
  },
  {
    name: "Estonia",
    officialName: "Republic of Estonia",
    alpha2: "EE",
    alpha3: "EST",
    numeric: "233",
    capital: "Tallinn",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Eesti",
    languages: ["Estonian"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+372",
    phoneMask: "+372 #### ####",
  },
  {
    name: "Eswatini",
    officialName: "Kingdom of Eswatini",
    alpha2: "SZ",
    alpha3: "SWZ",
    numeric: "748",
    capital: "Mbabane",
    region: "Africa",
    subregion: "Southern Africa",
    continent: "Africa",
    nativeName: "eSwatini",
    languages: ["English", "Swati"],
    currency: { code: "SZL", name: "Swazi lilangeni", symbol: "L" },
    phoneCode: "+268",
    phoneMask: "+268 #### ####",
  },
  {
    name: "Ethiopia",
    officialName: "Federal Democratic Republic of Ethiopia",
    alpha2: "ET",
    alpha3: "ETH",
    numeric: "231",
    capital: "Addis Ababa",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "ኢትዮጵያ",
    languages: ["Amharic"],
    currency: { code: "ETB", name: "Ethiopian birr", symbol: "Br" },
    phoneCode: "+251",
    phoneMask: "+251 ## ### ####",
  },
  {
    name: "Fiji",
    officialName: "Republic of Fiji",
    alpha2: "FJ",
    alpha3: "FJI",
    numeric: "242",
    capital: "Suva",
    region: "Oceania",
    subregion: "Melanesia",
    continent: "Oceania",
    nativeName: "Viti",
    languages: ["English", "Fijian", "Hindi"],
    currency: { code: "FJD", name: "Fijian dollar", symbol: "$" },
    phoneCode: "+679",
    phoneMask: "+679 ### ####",
  },
  {
    name: "Finland",
    officialName: "Republic of Finland",
    alpha2: "FI",
    alpha3: "FIN",
    numeric: "246",
    capital: "Helsinki",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Suomi",
    languages: ["Finnish", "Swedish"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+358",
    phoneMask: "+358 ## ### ####",
  },
  {
    name: "Gabon",
    officialName: "Gabonese Republic",
    alpha2: "GA",
    alpha3: "GAB",
    numeric: "266",
    capital: "Libreville",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "Gabon",
    languages: ["French"],
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+241",
    phoneMask: "+241 # ### ###",
  },
  {
    name: "Gambia",
    officialName: "Republic of The Gambia",
    alpha2: "GM",
    alpha3: "GMB",
    numeric: "270",
    capital: "Banjul",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Gambia",
    languages: ["English"],
    currency: { code: "GMD", name: "Gambian dalasi", symbol: "D" },
    phoneCode: "+220",
    phoneMask: "+220 ### ####",
  },
  {
    name: "Georgia",
    officialName: "Georgia",
    alpha2: "GE",
    alpha3: "GEO",
    numeric: "268",
    capital: "Tbilisi",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "საქართველო",
    languages: ["Georgian"],
    currency: { code: "GEL", name: "Georgian lari", symbol: "₾" },
    phoneCode: "+995",
    phoneMask: "+995 ### ### ###",
  },
  {
    name: "Ghana",
    officialName: "Republic of Ghana",
    alpha2: "GH",
    alpha3: "GHA",
    numeric: "288",
    capital: "Accra",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Ghana",
    languages: ["English"],
    currency: { code: "GHS", name: "Ghanaian cedi", symbol: "₵" },
    phoneCode: "+233",
    phoneMask: "+233 ## ### ####",
  },
  {
    name: "Greece",
    officialName: "Hellenic Republic",
    alpha2: "GR",
    alpha3: "GRC",
    numeric: "300",
    capital: "Athens",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Ελλάδα",
    languages: ["Greek"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+30",
    phoneMask: "+30 ### ### ####",
  },
  {
    name: "Grenada",
    officialName: "Grenada",
    alpha2: "GD",
    alpha3: "GRD",
    numeric: "308",
    capital: "St. George's",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Grenada",
    languages: ["English"],
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "+1-473",
    phoneMask: "+1 (473) ###-####",
  },
  {
    name: "Guatemala",
    officialName: "Republic of Guatemala",
    alpha2: "GT",
    alpha3: "GTM",
    numeric: "320",
    capital: "Guatemala City",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Guatemala",
    languages: ["Spanish"],
    currency: { code: "GTQ", name: "Guatemalan quetzal", symbol: "Q" },
    phoneCode: "+502",
    phoneMask: "+502 #### ####",
  },
  {
    name: "Guinea",
    officialName: "Republic of Guinea",
    alpha2: "GN",
    alpha3: "GIN",
    numeric: "324",
    capital: "Conakry",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Guinée",
    languages: ["French"],
    currency: { code: "GNF", name: "Guinean franc", symbol: "FG" },
    phoneCode: "+224",
    phoneMask: "+224 ### ### ###",
  },
  {
    name: "Guinea-Bissau",
    officialName: "Republic of Guinea-Bissau",
    alpha2: "GW",
    alpha3: "GNB",
    numeric: "624",
    capital: "Bissau",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Guiné-Bissau",
    languages: ["Portuguese"],
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+245",
    phoneMask: "+245 ### ### ###",
  },
  {
    name: "Guyana",
    officialName: "Co-operative Republic of Guyana",
    alpha2: "GY",
    alpha3: "GUY",
    numeric: "328",
    capital: "Georgetown",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Guyana",
    languages: ["English"],
    currency: { code: "GYD", name: "Guyanese dollar", symbol: "$" },
    phoneCode: "+592",
    phoneMask: "+592 ### ####",
  },
  {
    name: "Haiti",
    officialName: "Republic of Haiti",
    alpha2: "HT",
    alpha3: "HTI",
    numeric: "332",
    capital: "Port-au-Prince",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Haïti",
    languages: ["French", "Haitian Creole"],
    currency: { code: "HTG", name: "Haitian gourde", symbol: "G" },
    phoneCode: "+509",
    phoneMask: "+509 #### ####",
  },
  {
    name: "Honduras",
    officialName: "Republic of Honduras",
    alpha2: "HN",
    alpha3: "HND",
    numeric: "340",
    capital: "Tegucigalpa",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Honduras",
    languages: ["Spanish"],
    currency: { code: "HNL", name: "Honduran lempira", symbol: "L" },
    phoneCode: "+504",
    phoneMask: "+504 #### ####",
  },
  {
    name: "Hungary",
    officialName: "Hungary",
    alpha2: "HU",
    alpha3: "HUN",
    numeric: "348",
    capital: "Budapest",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Magyarország",
    languages: ["Hungarian"],
    currency: { code: "HUF", name: "Hungarian forint", symbol: "Ft" },
    phoneCode: "+36",
    phoneMask: "+36 ## ### ####",
  },
  {
    name: "Iceland",
    officialName: "Republic of Iceland",
    alpha2: "IS",
    alpha3: "ISL",
    numeric: "352",
    capital: "Reykjavik",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Ísland",
    languages: ["Icelandic"],
    currency: { code: "ISK", name: "Icelandic króna", symbol: "kr" },
    phoneCode: "+354",
    phoneMask: "+354 ### ####",
  },
  {
    name: "Indonesia",
    officialName: "Republic of Indonesia",
    alpha2: "ID",
    alpha3: "IDN",
    numeric: "360",
    capital: "Jakarta",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Indonesia",
    languages: ["Indonesian"],
    currency: { code: "IDR", name: "Indonesian rupiah", symbol: "Rp" },
    phoneCode: "+62",
    phoneMask: "+62 ### ### ####",
  },
  {
    name: "Iran",
    officialName: "Islamic Republic of Iran",
    alpha2: "IR",
    alpha3: "IRN",
    numeric: "364",
    capital: "Tehran",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "ایران",
    languages: ["Persian"],
    currency: { code: "IRR", name: "Iranian rial", symbol: "﷼" },
    phoneCode: "+98",
    phoneMask: "+98 ### ### ####",
  },
  {
    name: "Iraq",
    officialName: "Republic of Iraq",
    alpha2: "IQ",
    alpha3: "IRQ",
    numeric: "368",
    capital: "Baghdad",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "العراق",
    languages: ["Arabic", "Kurdish"],
    currency: { code: "IQD", name: "Iraqi dinar", symbol: "ع.د" },
    phoneCode: "+964",
    phoneMask: "+964 ### ### ####",
  },
  {
    name: "Ireland",
    officialName: "Republic of Ireland",
    alpha2: "IE",
    alpha3: "IRL",
    numeric: "372",
    capital: "Dublin",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Éire",
    languages: ["English", "Irish"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+353",
    phoneMask: "+353 ## ### ####",
  },
  {
    name: "Israel",
    officialName: "State of Israel",
    alpha2: "IL",
    alpha3: "ISR",
    numeric: "376",
    capital: "Jerusalem",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "ישראל",
    languages: ["Hebrew", "Arabic"],
    currency: { code: "ILS", name: "Israeli new shekel", symbol: "₪" },
    phoneCode: "+972",
    phoneMask: "+972 ## ### ####",
  },
  {
    name: "Italy",
    officialName: "Italian Republic",
    alpha2: "IT",
    alpha3: "ITA",
    numeric: "380",
    capital: "Rome",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Italia",
    languages: ["Italian"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+39",
    phoneMask: "+39 ### ### ####",
  },
  {
    name: "Jamaica",
    officialName: "Jamaica",
    alpha2: "JM",
    alpha3: "JAM",
    numeric: "388",
    capital: "Kingston",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Jamaica",
    languages: ["English"],
    currency: { code: "JMD", name: "Jamaican dollar", symbol: "$" },
    phoneCode: "+1-876",
    phoneMask: "+1 (876) ###-####",
  },
  {
    name: "Jordan",
    officialName: "Hashemite Kingdom of Jordan",
    alpha2: "JO",
    alpha3: "JOR",
    numeric: "400",
    capital: "Amman",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "الأردن",
    languages: ["Arabic"],
    currency: { code: "JOD", name: "Jordanian dinar", symbol: "د.ا" },
    phoneCode: "+962",
    phoneMask: "+962 # #### ####",
  },
  {
    name: "Kazakhstan",
    officialName: "Republic of Kazakhstan",
    alpha2: "KZ",
    alpha3: "KAZ",
    numeric: "398",
    capital: "Astana",
    region: "Asia",
    subregion: "Central Asia",
    continent: "Asia",
    nativeName: "Қазақстан",
    languages: ["Kazakh", "Russian"],
    currency: { code: "KZT", name: "Kazakhstani tenge", symbol: "₸" },
    phoneCode: "+7",
    phoneMask: "+7 ### ### ####",
  },
  {
    name: "Kenya",
    officialName: "Republic of Kenya",
    alpha2: "KE",
    alpha3: "KEN",
    numeric: "404",
    capital: "Nairobi",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Kenya",
    languages: ["English", "Swahili"],
    currency: { code: "KES", name: "Kenyan shilling", symbol: "KSh" },
    phoneCode: "+254",
    phoneMask: "+254 ### ### ###",
  },
  {
    name: "Kiribati",
    officialName: "Republic of Kiribati",
    alpha2: "KI",
    alpha3: "KIR",
    numeric: "296",
    capital: "Tarawa",
    region: "Oceania",
    subregion: "Micronesia",
    continent: "Oceania",
    nativeName: "Kiribati",
    languages: ["English", "Gilbertese"],
    currency: { code: "AUD", name: "Australian dollar", symbol: "$" },
    phoneCode: "+686",
    phoneMask: "+686 #####",
  },
  {
    name: "Kuwait",
    officialName: "State of Kuwait",
    alpha2: "KW",
    alpha3: "KWT",
    numeric: "414",
    capital: "Kuwait City",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "الكويت",
    languages: ["Arabic"],
    currency: { code: "KWD", name: "Kuwaiti dinar", symbol: "د.ك" },
    phoneCode: "+965",
    phoneMask: "+965 #### ####",
  },
  {
    name: "Kyrgyzstan",
    officialName: "Kyrgyz Republic",
    alpha2: "KG",
    alpha3: "KGZ",
    numeric: "417",
    capital: "Bishkek",
    region: "Asia",
    subregion: "Central Asia",
    continent: "Asia",
    nativeName: "Кыргызстан",
    languages: ["Kyrgyz", "Russian"],
    currency: { code: "KGS", name: "Kyrgyzstani som", symbol: "с" },
    phoneCode: "+996",
    phoneMask: "+996 ### ### ###",
  },
  {
    name: "Laos",
    officialName: "Lao People's Democratic Republic",
    alpha2: "LA",
    alpha3: "LAO",
    numeric: "418",
    capital: "Vientiane",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "ລາວ",
    languages: ["Lao"],
    currency: { code: "LAK", name: "Lao kip", symbol: "₭" },
    phoneCode: "+856",
    phoneMask: "+856 ## ### ####",
  },
  {
    name: "Latvia",
    officialName: "Republic of Latvia",
    alpha2: "LV",
    alpha3: "LVA",
    numeric: "428",
    capital: "Riga",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Latvija",
    languages: ["Latvian"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+371",
    phoneMask: "+371 #### ####",
  },
  {
    name: "Lebanon",
    officialName: "Lebanese Republic",
    alpha2: "LB",
    alpha3: "LBN",
    numeric: "422",
    capital: "Beirut",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "لبنان",
    languages: ["Arabic", "French"],
    currency: { code: "LBP", name: "Lebanese pound", symbol: "ل.ل" },
    phoneCode: "+961",
    phoneMask: "+961 ## ### ###",
  },
  {
    name: "Lesotho",
    officialName: "Kingdom of Lesotho",
    alpha2: "LS",
    alpha3: "LSO",
    numeric: "426",
    capital: "Maseru",
    region: "Africa",
    subregion: "Southern Africa",
    continent: "Africa",
    nativeName: "Lesotho",
    languages: ["English", "Sesotho"],
    currency: { code: "LSL", name: "Lesotho loti", symbol: "L" },
    phoneCode: "+266",
    phoneMask: "+266 #### ####",
  },
  {
    name: "Liberia",
    officialName: "Republic of Liberia",
    alpha2: "LR",
    alpha3: "LBR",
    numeric: "430",
    capital: "Monrovia",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Liberia",
    languages: ["English"],
    currency: { code: "LRD", name: "Liberian dollar", symbol: "$" },
    phoneCode: "+231",
    phoneMask: "+231 ## ### ####",
  },
  {
    name: "Libya",
    officialName: "State of Libya",
    alpha2: "LY",
    alpha3: "LBY",
    numeric: "434",
    capital: "Tripoli",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "ليبيا",
    languages: ["Arabic"],
    currency: { code: "LYD", name: "Libyan dinar", symbol: "ل.د" },
    phoneCode: "+218",
    phoneMask: "+218 ## ### ####",
  },
  {
    name: "Liechtenstein",
    officialName: "Principality of Liechtenstein",
    alpha2: "LI",
    alpha3: "LIE",
    numeric: "438",
    capital: "Vaduz",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Liechtenstein",
    languages: ["German"],
    currency: { code: "CHF", name: "Swiss franc", symbol: "CHF" },
    phoneCode: "+423",
    phoneMask: "+423 ### ### ###",
  },
  {
    name: "Lithuania",
    officialName: "Republic of Lithuania",
    alpha2: "LT",
    alpha3: "LTU",
    numeric: "440",
    capital: "Vilnius",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Lietuva",
    languages: ["Lithuanian"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+370",
    phoneMask: "+370 ### ### ##",
  },
  {
    name: "Luxembourg",
    officialName: "Grand Duchy of Luxembourg",
    alpha2: "LU",
    alpha3: "LUX",
    numeric: "442",
    capital: "Luxembourg",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Lëtzebuerg",
    languages: ["French", "German", "Luxembourgish"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+352",
    phoneMask: "+352 ### ### ###",
  },
  {
    name: "Madagascar",
    officialName: "Republic of Madagascar",
    alpha2: "MG",
    alpha3: "MDG",
    numeric: "450",
    capital: "Antananarivo",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Madagasikara",
    languages: ["Malagasy", "French"],
    currency: { code: "MGA", name: "Malagasy ariary", symbol: "Ar" },
    phoneCode: "+261",
    phoneMask: "+261 ## ### ####",
  },
  {
    name: "Malawi",
    officialName: "Republic of Malawi",
    alpha2: "MW",
    alpha3: "MWI",
    numeric: "454",
    capital: "Lilongwe",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Malawi",
    languages: ["English", "Chewa"],
    currency: { code: "MWK", name: "Malawian kwacha", symbol: "MK" },
    phoneCode: "+265",
    phoneMask: "+265 # ### ####",
  },
  {
    name: "Malaysia",
    officialName: "Malaysia",
    alpha2: "MY",
    alpha3: "MYS",
    numeric: "458",
    capital: "Kuala Lumpur",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Malaysia",
    languages: ["Malay"],
    currency: { code: "MYR", name: "Malaysian ringgit", symbol: "RM" },
    phoneCode: "+60",
    phoneMask: "+60 ## ### ####",
  },
  {
    name: "Maldives",
    officialName: "Republic of Maldives",
    alpha2: "MV",
    alpha3: "MDV",
    numeric: "462",
    capital: "Malé",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "ދިވެހިރާއްޖެ",
    languages: ["Dhivehi"],
    currency: { code: "MVR", name: "Maldivian rufiyaa", symbol: "Rf" },
    phoneCode: "+960",
    phoneMask: "+960 ### ####",
  },
  {
    name: "Mali",
    officialName: "Republic of Mali",
    alpha2: "ML",
    alpha3: "MLI",
    numeric: "466",
    capital: "Bamako",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Mali",
    languages: ["French"],
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+223",
    phoneMask: "+223 #### ####",
  },
  {
    name: "Malta",
    officialName: "Republic of Malta",
    alpha2: "MT",
    alpha3: "MLT",
    numeric: "470",
    capital: "Valletta",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Malta",
    languages: ["Maltese", "English"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+356",
    phoneMask: "+356 #### ####",
  },
  {
    name: "Marshall Islands",
    officialName: "Republic of the Marshall Islands",
    alpha2: "MH",
    alpha3: "MHL",
    numeric: "584",
    capital: "Majuro",
    region: "Oceania",
    subregion: "Micronesia",
    continent: "Oceania",
    nativeName: "M̧ajeļ",
    languages: ["English", "Marshallese"],
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "+692",
    phoneMask: "+692 ### ####",
  },
  {
    name: "Mauritania",
    officialName: "Islamic Republic of Mauritania",
    alpha2: "MR",
    alpha3: "MRT",
    numeric: "478",
    capital: "Nouakchott",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "موريتانيا",
    languages: ["Arabic"],
    currency: {
      code: "MRU",
      name: "Mauritanian ouguiya",
      symbol: "UM",
    },
    phoneCode: "+222",
    phoneMask: "+222 ## ### ###",
  },
  {
    name: "Mauritius",
    officialName: "Republic of Mauritius",
    alpha2: "MU",
    alpha3: "MUS",
    numeric: "480",
    capital: "Port Louis",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Maurice",
    languages: ["English", "French"],
    currency: { code: "MUR", name: "Mauritian rupee", symbol: "₨" },
    phoneCode: "+230",
    phoneMask: "+230 #### ####",
  },
  {
    name: "Micronesia",
    officialName: "Federated States of Micronesia",
    alpha2: "FM",
    alpha3: "FSM",
    numeric: "583",
    capital: "Palikir",
    region: "Oceania",
    subregion: "Micronesia",
    continent: "Oceania",
    nativeName: "Micronesia",
    languages: ["English"],
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "+691",
    phoneMask: "+691 ### ####",
  },
  {
    name: "Moldova",
    officialName: "Republic of Moldova",
    alpha2: "MD",
    alpha3: "MDA",
    numeric: "498",
    capital: "Chișinău",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Moldova",
    languages: ["Romanian"],
    currency: { code: "MDL", name: "Moldovan leu", symbol: "L" },
    phoneCode: "+373",
    phoneMask: "+373 #### ####",
  },
  {
    name: "Monaco",
    officialName: "Principality of Monaco",
    alpha2: "MC",
    alpha3: "MCO",
    numeric: "492",
    capital: "Monaco",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Monaco",
    languages: ["French"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+377",
    phoneMask: "+377 ## ### ###",
  },
  {
    name: "Mongolia",
    officialName: "Mongolia",
    alpha2: "MN",
    alpha3: "MNG",
    numeric: "496",
    capital: "Ulaanbaatar",
    region: "Asia",
    subregion: "Eastern Asia",
    continent: "Asia",
    nativeName: "Монгол Улс",
    languages: ["Mongolian"],
    currency: { code: "MNT", name: "Mongolian tögrög", symbol: "₮" },
    phoneCode: "+976",
    phoneMask: "+976 ## ### ###",
  },
  {
    name: "Montenegro",
    officialName: "Montenegro",
    alpha2: "ME",
    alpha3: "MNE",
    numeric: "499",
    capital: "Podgorica",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Crna Gora",
    languages: ["Montenegrin"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+382",
    phoneMask: "+382 ## ### ###",
  },
  {
    name: "Morocco",
    officialName: "Kingdom of Morocco",
    alpha2: "MA",
    alpha3: "MAR",
    numeric: "504",
    capital: "Rabat",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "المغرب",
    languages: ["Arabic", "Berber"],
    currency: { code: "MAD", name: "Moroccan dirham", symbol: "د.م." },
    phoneCode: "+212",
    phoneMask: "+212 ## ### ####",
  },
  {
    name: "Mozambique",
    officialName: "Republic of Mozambique",
    alpha2: "MZ",
    alpha3: "MOZ",
    numeric: "508",
    capital: "Maputo",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Moçambique",
    languages: ["Portuguese"],
    currency: { code: "MZN", name: "Mozambican metical", symbol: "MT" },
    phoneCode: "+258",
    phoneMask: "+258 ## ### ###",
  },
  {
    name: "Myanmar",
    officialName: "Republic of the Union of Myanmar",
    alpha2: "MM",
    alpha3: "MMR",
    numeric: "104",
    capital: "Naypyidaw",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "မြန်မာ",
    languages: ["Burmese"],
    currency: { code: "MMK", name: "Myanmar kyat", symbol: "K" },
    phoneCode: "+95",
    phoneMask: "+95 ## ### ####",
  },
  {
    name: "Namibia",
    officialName: "Republic of Namibia",
    alpha2: "NA",
    alpha3: "NAM",
    numeric: "516",
    capital: "Windhoek",
    region: "Africa",
    subregion: "Southern Africa",
    continent: "Africa",
    nativeName: "Namibia",
    languages: ["English"],
    currency: { code: "NAD", name: "Namibian dollar", symbol: "$" },
    phoneCode: "+264",
    phoneMask: "+264 ## ### ####",
  },
  {
    name: "Nauru",
    officialName: "Republic of Nauru",
    alpha2: "NR",
    alpha3: "NRU",
    numeric: "520",
    capital: "Yaren",
    region: "Oceania",
    subregion: "Micronesia",
    continent: "Oceania",
    nativeName: "Nauru",
    languages: ["English", "Nauruan"],
    currency: { code: "AUD", name: "Australian dollar", symbol: "$" },
    phoneCode: "+674",
    phoneMask: "+674 ### ####",
  },
  {
    name: "Nepal",
    officialName: "Federal Democratic Republic of Nepal",
    alpha2: "NP",
    alpha3: "NPL",
    numeric: "524",
    capital: "Kathmandu",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "नेपाल",
    languages: ["Nepali"],
    currency: { code: "NPR", name: "Nepalese rupee", symbol: "₨" },
    phoneCode: "+977",
    phoneMask: "+977 ## ### ####",
  },
  {
    name: "Netherlands",
    officialName: "Kingdom of the Netherlands",
    alpha2: "NL",
    alpha3: "NLD",
    numeric: "528",
    capital: "Amsterdam",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Nederland",
    languages: ["Dutch"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+31",
    phoneMask: "+31 ## ### ####",
  },
  {
    name: "New Zealand",
    officialName: "New Zealand",
    alpha2: "NZ",
    alpha3: "NZL",
    numeric: "554",
    capital: "Wellington",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    continent: "Oceania",
    nativeName: "Aotearoa",
    languages: ["English", "Māori"],
    currency: { code: "NZD", name: "New Zealand dollar", symbol: "$" },
    phoneCode: "+64",
    phoneMask: "+64 ### ### ###",
  },
  {
    name: "Nicaragua",
    officialName: "Republic of Nicaragua",
    alpha2: "NI",
    alpha3: "NIC",
    numeric: "558",
    capital: "Managua",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Nicaragua",
    languages: ["Spanish"],
    currency: { code: "NIO", name: "Nicaraguan córdoba", symbol: "C$" },
    phoneCode: "+505",
    phoneMask: "+505 #### ####",
  },
  {
    name: "Niger",
    officialName: "Republic of Niger",
    alpha2: "NE",
    alpha3: "NER",
    numeric: "562",
    capital: "Niamey",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Niger",
    languages: ["French"],
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+227",
    phoneMask: "+227 ## ### ###",
  },
  {
    name: "North Korea",
    officialName: "Democratic People's Republic of Korea",
    alpha2: "KP",
    alpha3: "PRK",
    numeric: "408",
    capital: "Pyongyang",
    region: "Asia",
    subregion: "Eastern Asia",
    continent: "Asia",
    nativeName: "조선",
    languages: ["Korean"],
    currency: { code: "KPW", name: "North Korean won", symbol: "₩" },
    phoneCode: "+850",
    phoneMask: "+850 ### ### ###",
  },
  {
    name: "North Macedonia",
    officialName: "Republic of North Macedonia",
    alpha2: "MK",
    alpha3: "MKD",
    numeric: "807",
    capital: "Skopje",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Северна Македонија",
    languages: ["Macedonian"],
    currency: { code: "MKD", name: "Macedonian denar", symbol: "ден" },
    phoneCode: "+389",
    phoneMask: "+389 ## ### ###",
  },
  {
    name: "Norway",
    officialName: "Kingdom of Norway",
    alpha2: "NO",
    alpha3: "NOR",
    numeric: "578",
    capital: "Oslo",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Norge",
    languages: ["Norwegian"],
    currency: { code: "NOK", name: "Norwegian krone", symbol: "kr" },
    phoneCode: "+47",
    phoneMask: "+47 ### ## ###",
  },
  {
    name: "Oman",
    officialName: "Sultanate of Oman",
    alpha2: "OM",
    alpha3: "OMN",
    numeric: "512",
    capital: "Muscat",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "عمان",
    languages: ["Arabic"],
    currency: { code: "OMR", name: "Omani rial", symbol: "ر.ع." },
    phoneCode: "+968",
    phoneMask: "+968 #### ####",
  },
  {
    name: "Pakistan",
    officialName: "Islamic Republic of Pakistan",
    alpha2: "PK",
    alpha3: "PAK",
    numeric: "586",
    capital: "Islamabad",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "پاکستان",
    languages: ["Urdu", "English"],
    currency: { code: "PKR", name: "Pakistani rupee", symbol: "₨" },
    phoneCode: "+92",
    phoneMask: "+92 ### ### ####",
  },
  {
    name: "Palau",
    officialName: "Republic of Palau",
    alpha2: "PW",
    alpha3: "PLW",
    numeric: "585",
    capital: "Ngerulmud",
    region: "Oceania",
    subregion: "Micronesia",
    continent: "Oceania",
    nativeName: "Belau",
    languages: ["English", "Palauan"],
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "+680",
    phoneMask: "+680 ### ####",
  },
  {
    name: "Panama",
    officialName: "Republic of Panama",
    alpha2: "PA",
    alpha3: "PAN",
    numeric: "591",
    capital: "Panama City",
    region: "Americas",
    subregion: "Central America",
    continent: "North America",
    nativeName: "Panamá",
    languages: ["Spanish"],
    currency: { code: "PAB", name: "Panamanian balboa", symbol: "B/." },
    phoneCode: "+507",
    phoneMask: "+507 #### ####",
  },
  {
    name: "Papua New Guinea",
    officialName: "Independent State of Papua New Guinea",
    alpha2: "PG",
    alpha3: "PNG",
    numeric: "598",
    capital: "Port Moresby",
    region: "Oceania",
    subregion: "Melanesia",
    continent: "Oceania",
    nativeName: "Papua Niugini",
    languages: ["English", "Tok Pisin", "Hiri Motu"],
    currency: {
      code: "PGK",
      name: "Papua New Guinean kina",
      symbol: "K",
    },
    phoneCode: "+675",
    phoneMask: "+675 ### ####",
  },
  {
    name: "Paraguay",
    officialName: "Republic of Paraguay",
    alpha2: "PY",
    alpha3: "PRY",
    numeric: "600",
    capital: "Asunción",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Paraguay",
    languages: ["Spanish", "Guarani"],
    currency: { code: "PYG", name: "Paraguayan guaraní", symbol: "₲" },
    phoneCode: "+595",
    phoneMask: "+595 ### ### ###",
  },
  {
    name: "Peru",
    officialName: "Republic of Peru",
    alpha2: "PE",
    alpha3: "PER",
    numeric: "604",
    capital: "Lima",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Perú",
    languages: ["Spanish", "Quechua", "Aymara"],
    currency: { code: "PEN", name: "Peruvian sol", symbol: "S/." },
    phoneCode: "+51",
    phoneMask: "+51 ### ### ###",
  },
  {
    name: "Philippines",
    officialName: "Republic of the Philippines",
    alpha2: "PH",
    alpha3: "PHL",
    numeric: "608",
    capital: "Manila",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Pilipinas",
    languages: ["Filipino", "English"],
    currency: { code: "PHP", name: "Philippine peso", symbol: "₱" },
    phoneCode: "+63",
    phoneMask: "+63 ### ### ####",
  },
  {
    name: "Poland",
    officialName: "Republic of Poland",
    alpha2: "PL",
    alpha3: "POL",
    numeric: "616",
    capital: "Warsaw",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Polska",
    languages: ["Polish"],
    currency: { code: "PLN", name: "Polish złoty", symbol: "zł" },
    phoneCode: "+48",
    phoneMask: "+48 ### ### ###",
  },
  {
    name: "Portugal",
    officialName: "Portuguese Republic",
    alpha2: "PT",
    alpha3: "PRT",
    numeric: "620",
    capital: "Lisbon",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Portugal",
    languages: ["Portuguese"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+351",
    phoneMask: "+351 ### ### ###",
  },
  {
    name: "Qatar",
    officialName: "State of Qatar",
    alpha2: "QA",
    alpha3: "QAT",
    numeric: "634",
    capital: "Doha",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "قطر",
    languages: ["Arabic"],
    currency: { code: "QAR", name: "Qatari riyal", symbol: "ر.ق" },
    phoneCode: "+974",
    phoneMask: "+974 #### ####",
  },
  {
    name: "Romania",
    officialName: "Romania",
    alpha2: "RO",
    alpha3: "ROU",
    numeric: "642",
    capital: "Bucharest",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "România",
    languages: ["Romanian"],
    currency: { code: "RON", name: "Romanian leu", symbol: "lei" },
    phoneCode: "+40",
    phoneMask: "+40 ### ### ###",
  },
  {
    name: "Rwanda",
    officialName: "Republic of Rwanda",
    alpha2: "RW",
    alpha3: "RWA",
    numeric: "646",
    capital: "Kigali",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Rwanda",
    languages: ["Kinyarwanda", "English", "French"],
    currency: { code: "RWF", name: "Rwandan franc", symbol: "FRw" },
    phoneCode: "+250",
    phoneMask: "+250 ### ### ###",
  },
  {
    name: "Saint Kitts and Nevis",
    officialName: "Federation of Saint Christopher and Nevis",
    alpha2: "KN",
    alpha3: "KNA",
    numeric: "659",
    capital: "Basseterre",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Saint Kitts and Nevis",
    languages: ["English"],
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "+1-869",
    phoneMask: "+1 (869) ###-####",
  },
  {
    name: "Saint Lucia",
    officialName: "Saint Lucia",
    alpha2: "LC",
    alpha3: "LCA",
    numeric: "662",
    capital: "Castries",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Saint Lucia",
    languages: ["English"],
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "+1-758",
    phoneMask: "+1 (758) ###-####",
  },
  {
    name: "Saint Vincent and the Grenadines",
    officialName: "Saint Vincent and the Grenadines",
    alpha2: "VC",
    alpha3: "VCT",
    numeric: "670",
    capital: "Kingstown",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Saint Vincent and the Grenadines",
    languages: ["English"],
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    phoneCode: "+1-784",
    phoneMask: "+1 (784) ###-####",
  },
  {
    name: "Samoa",
    officialName: "Independent State of Samoa",
    alpha2: "WS",
    alpha3: "WSM",
    numeric: "882",
    capital: "Apia",
    region: "Oceania",
    subregion: "Polynesia",
    continent: "Oceania",
    nativeName: "Sāmoa",
    languages: ["Samoan", "English"],
    currency: { code: "WST", name: "Samoan tālā", symbol: "T" },
    phoneCode: "+685",
    phoneMask: "+685 #####",
  },
  {
    name: "San Marino",
    officialName: "Republic of San Marino",
    alpha2: "SM",
    alpha3: "SMR",
    numeric: "674",
    capital: "San Marino",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "San Marino",
    languages: ["Italian"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+378",
    phoneMask: "+378 #### ######",
  },
  {
    name: "Sao Tome and Principe",
    officialName: "Democratic Republic of Sao Tome and Principe",
    alpha2: "ST",
    alpha3: "STP",
    numeric: "678",
    capital: "São Tomé",
    region: "Africa",
    subregion: "Middle Africa",
    continent: "Africa",
    nativeName: "São Tomé e Príncipe",
    languages: ["Portuguese"],
    currency: {
      code: "STN",
      name: "São Tomé and Príncipe dobra",
      symbol: "Db",
    },
    phoneCode: "+239",
    phoneMask: "+239 ### ####",
  },
  {
    name: "Senegal",
    officialName: "Republic of Senegal",
    alpha2: "SN",
    alpha3: "SEN",
    numeric: "686",
    capital: "Dakar",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Sénégal",
    languages: ["French"],
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+221",
    phoneMask: "+221 ## ### ####",
  },
  {
    name: "Serbia",
    officialName: "Republic of Serbia",
    alpha2: "RS",
    alpha3: "SRB",
    numeric: "688",
    capital: "Belgrade",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Србија",
    languages: ["Serbian"],
    currency: { code: "RSD", name: "Serbian dinar", symbol: "din." },
    phoneCode: "+381",
    phoneMask: "+381 ## ### ####",
  },
  {
    name: "Seychelles",
    officialName: "Republic of Seychelles",
    alpha2: "SC",
    alpha3: "SYC",
    numeric: "690",
    capital: "Victoria",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Sesel",
    languages: ["English", "French", "Seychellois Creole"],
    currency: { code: "SCR", name: "Seychellois rupee", symbol: "₨" },
    phoneCode: "+248",
    phoneMask: "+248 #### ###",
  },
  {
    name: "Sierra Leone",
    officialName: "Republic of Sierra Leone",
    alpha2: "SL",
    alpha3: "SLE",
    numeric: "694",
    capital: "Freetown",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Sierra Leone",
    languages: ["English"],
    currency: {
      code: "SLL",
      name: "Sierra Leonean leone",
      symbol: "Le",
    },
    phoneCode: "+232",
    phoneMask: "+232 ## ### ###",
  },
  {
    name: "Singapore",
    officialName: "Republic of Singapore",
    alpha2: "SG",
    alpha3: "SGP",
    numeric: "702",
    capital: "Singapore",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Singapore",
    languages: ["English", "Malay", "Mandarin", "Tamil"],
    currency: { code: "SGD", name: "Singapore dollar", symbol: "$" },
    phoneCode: "+65",
    phoneMask: "+65 #### ####",
  },
  {
    name: "Slovakia",
    officialName: "Slovak Republic",
    alpha2: "SK",
    alpha3: "SVK",
    numeric: "703",
    capital: "Bratislava",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Slovensko",
    languages: ["Slovak"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+421",
    phoneMask: "+421 ### ### ###",
  },
  {
    name: "Slovenia",
    officialName: "Republic of Slovenia",
    alpha2: "SI",
    alpha3: "SVN",
    numeric: "705",
    capital: "Ljubljana",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "Slovenija",
    languages: ["Slovenian"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+386",
    phoneMask: "+386 ## ### ###",
  },
  {
    name: "Solomon Islands",
    officialName: "Solomon Islands",
    alpha2: "SB",
    alpha3: "SLB",
    numeric: "090",
    capital: "Honiara",
    region: "Oceania",
    subregion: "Melanesia",
    continent: "Oceania",
    nativeName: "Solomon Islands",
    languages: ["English"],
    currency: {
      code: "SBD",
      name: "Solomon Islands dollar",
      symbol: "$",
    },
    phoneCode: "+677",
    phoneMask: "+677 #####",
  },
  {
    name: "Somalia",
    officialName: "Federal Republic of Somalia",
    alpha2: "SO",
    alpha3: "SOM",
    numeric: "706",
    capital: "Mogadishu",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Soomaaliya",
    languages: ["Somali", "Arabic"],
    currency: { code: "SOS", name: "Somali shilling", symbol: "Sh" },
    phoneCode: "+252",
    phoneMask: "+252 ## ### ###",
  },
  {
    name: "South Korea",
    officialName: "Republic of Korea",
    alpha2: "KR",
    alpha3: "KOR",
    numeric: "410",
    capital: "Seoul",
    region: "Asia",
    subregion: "Eastern Asia",
    continent: "Asia",
    nativeName: "대한민국",
    languages: ["Korean"],
    currency: { code: "KRW", name: "South Korean won", symbol: "₩" },
    phoneCode: "+82",
    phoneMask: "+82 ## ### ####",
  },
  {
    name: "South Sudan",
    officialName: "Republic of South Sudan",
    alpha2: "SS",
    alpha3: "SSD",
    numeric: "728",
    capital: "Juba",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "South Sudan",
    languages: ["English"],
    currency: {
      code: "SSP",
      name: "South Sudanese pound",
      symbol: "£",
    },
    phoneCode: "+211",
    phoneMask: "+211 ### ### ###",
  },
  {
    name: "Spain",
    officialName: "Kingdom of Spain",
    alpha2: "ES",
    alpha3: "ESP",
    numeric: "724",
    capital: "Madrid",
    region: "Europe",
    subregion: "Southern Europe",
    continent: "Europe",
    nativeName: "España",
    languages: ["Spanish"],
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    phoneCode: "+34",
    phoneMask: "+34 ### ### ###",
  },
  {
    name: "Sri Lanka",
    officialName: "Democratic Socialist Republic of Sri Lanka",
    alpha2: "LK",
    alpha3: "LKA",
    numeric: "144",
    capital: "Colombo",
    region: "Asia",
    subregion: "Southern Asia",
    continent: "Asia",
    nativeName: "ශ්‍රී ලංකා",
    languages: ["Sinhala", "Tamil"],
    currency: { code: "LKR", name: "Sri Lankan rupee", symbol: "₨" },
    phoneCode: "+94",
    phoneMask: "+94 ## ### ####",
  },
  {
    name: "Sudan",
    officialName: "Republic of the Sudan",
    alpha2: "SD",
    alpha3: "SDN",
    numeric: "729",
    capital: "Khartoum",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "السودان",
    languages: ["Arabic", "English"],
    currency: { code: "SDG", name: "Sudanese pound", symbol: "£" },
    phoneCode: "+249",
    phoneMask: "+249 ## ### ####",
  },
  {
    name: "Suriname",
    officialName: "Republic of Suriname",
    alpha2: "SR",
    alpha3: "SUR",
    numeric: "740",
    capital: "Paramaribo",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Suriname",
    languages: ["Dutch"],
    currency: { code: "SRD", name: "Surinamese dollar", symbol: "$" },
    phoneCode: "+597",
    phoneMask: "+597 ### ####",
  },
  {
    name: "Sweden",
    officialName: "Kingdom of Sweden",
    alpha2: "SE",
    alpha3: "SWE",
    numeric: "752",
    capital: "Stockholm",
    region: "Europe",
    subregion: "Northern Europe",
    continent: "Europe",
    nativeName: "Sverige",
    languages: ["Swedish"],
    currency: { code: "SEK", name: "Swedish krona", symbol: "kr" },
    phoneCode: "+46",
    phoneMask: "+46 ## ### ####",
  },
  {
    name: "Switzerland",
    officialName: "Swiss Confederation",
    alpha2: "CH",
    alpha3: "CHE",
    numeric: "756",
    capital: "Bern",
    region: "Europe",
    subregion: "Western Europe",
    continent: "Europe",
    nativeName: "Schweiz",
    languages: ["German", "French", "Italian", "Romansh"],
    currency: { code: "CHF", name: "Swiss franc", symbol: "CHF" },
    phoneCode: "+41",
    phoneMask: "+41 ## ### ####",
  },
  {
    name: "Syria",
    officialName: "Syrian Arab Republic",
    alpha2: "SY",
    alpha3: "SYR",
    numeric: "760",
    capital: "Damascus",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "سوريا",
    languages: ["Arabic"],
    currency: { code: "SYP", name: "Syrian pound", symbol: "£" },
    phoneCode: "+963",
    phoneMask: "+963 ### ### ###",
  },
  {
    name: "Tajikistan",
    officialName: "Republic of Tajikistan",
    alpha2: "TJ",
    alpha3: "TJK",
    numeric: "762",
    capital: "Dushanbe",
    region: "Asia",
    subregion: "Central Asia",
    continent: "Asia",
    nativeName: "Тоҷикистон",
    languages: ["Tajik"],
    currency: { code: "TJS", name: "Tajikistani somoni", symbol: "SM" },
    phoneCode: "+992",
    phoneMask: "+992 ### ### ###",
  },
  {
    name: "Tanzania",
    officialName: "United Republic of Tanzania",
    alpha2: "TZ",
    alpha3: "TZA",
    numeric: "834",
    capital: "Dodoma",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Tanzania",
    languages: ["Swahili", "English"],
    currency: {
      code: "TZS",
      name: "Tanzanian shilling",
      symbol: "TSh",
    },
    phoneCode: "+255",
    phoneMask: "+255 ### ### ###",
  },
  {
    name: "Thailand",
    officialName: "Kingdom of Thailand",
    alpha2: "TH",
    alpha3: "THA",
    numeric: "764",
    capital: "Bangkok",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "ประเทศไทย",
    languages: ["Thai"],
    currency: { code: "THB", name: "Thai baht", symbol: "฿" },
    phoneCode: "+66",
    phoneMask: "+66 ## ### ####",
  },
  {
    name: "Togo",
    officialName: "Togolese Republic",
    alpha2: "TG",
    alpha3: "TGO",
    numeric: "768",
    capital: "Lomé",
    region: "Africa",
    subregion: "Western Africa",
    continent: "Africa",
    nativeName: "Togo",
    languages: ["French"],
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "CFA",
    },
    phoneCode: "+228",
    phoneMask: "+228 ## ### ###",
  },
  {
    name: "Tonga",
    officialName: "Kingdom of Tonga",
    alpha2: "TO",
    alpha3: "TON",
    numeric: "776",
    capital: "Nukuʻalofa",
    region: "Oceania",
    subregion: "Polynesia",
    continent: "Oceania",
    nativeName: "Tonga",
    languages: ["Tongan", "English"],
    currency: { code: "TOP", name: "Tongan paʻanga", symbol: "T$" },
    phoneCode: "+676",
    phoneMask: "+676 #####",
  },
  {
    name: "Trinidad and Tobago",
    officialName: "Republic of Trinidad and Tobago",
    alpha2: "TT",
    alpha3: "TTO",
    numeric: "780",
    capital: "Port of Spain",
    region: "Americas",
    subregion: "Caribbean",
    continent: "North America",
    nativeName: "Trinidad and Tobago",
    languages: ["English"],
    currency: {
      code: "TTD",
      name: "Trinidad and Tobago dollar",
      symbol: "$",
    },
    phoneCode: "+1-868",
    phoneMask: "+1 (868) ###-####",
  },
  {
    name: "Tunisia",
    officialName: "Republic of Tunisia",
    alpha2: "TN",
    alpha3: "TUN",
    numeric: "788",
    capital: "Tunis",
    region: "Africa",
    subregion: "Northern Africa",
    continent: "Africa",
    nativeName: "تونس",
    languages: ["Arabic"],
    currency: { code: "TND", name: "Tunisian dinar", symbol: "د.ت" },
    phoneCode: "+216",
    phoneMask: "+216 ## ### ###",
  },
  {
    name: "Turkey",
    officialName: "Republic of Türkiye",
    alpha2: "TR",
    alpha3: "TUR",
    numeric: "792",
    capital: "Ankara",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "Türkiye",
    languages: ["Turkish"],
    currency: { code: "TRY", name: "Turkish lira", symbol: "₺" },
    phoneCode: "+90",
    phoneMask: "+90 ### ### ####",
  },
  {
    name: "Turkmenistan",
    officialName: "Turkmenistan",
    alpha2: "TM",
    alpha3: "TKM",
    numeric: "795",
    capital: "Ashgabat",
    region: "Asia",
    subregion: "Central Asia",
    continent: "Asia",
    nativeName: "Türkmenistan",
    languages: ["Turkmen"],
    currency: { code: "TMT", name: "Turkmenistan manat", symbol: "m" },
    phoneCode: "+993",
    phoneMask: "+993 ## ### ###",
  },
  {
    name: "Tuvalu",
    officialName: "Tuvalu",
    alpha2: "TV",
    alpha3: "TUV",
    numeric: "798",
    capital: "Funafuti",
    region: "Oceania",
    subregion: "Polynesia",
    continent: "Oceania",
    nativeName: "Tuvalu",
    languages: ["English", "Tuvaluan"],
    currency: { code: "AUD", name: "Australian dollar", symbol: "$" },
    phoneCode: "+688",
    phoneMask: "+688 #####",
  },
  {
    name: "Uganda",
    officialName: "Republic of Uganda",
    alpha2: "UG",
    alpha3: "UGA",
    numeric: "800",
    capital: "Kampala",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Uganda",
    languages: ["English", "Swahili"],
    currency: { code: "UGX", name: "Ugandan shilling", symbol: "USh" },
    phoneCode: "+256",
    phoneMask: "+256 ### ### ###",
  },
  {
    name: "Ukraine",
    officialName: "Ukraine",
    alpha2: "UA",
    alpha3: "UKR",
    numeric: "804",
    capital: "Kyiv",
    region: "Europe",
    subregion: "Eastern Europe",
    continent: "Europe",
    nativeName: "Україна",
    languages: ["Ukrainian"],
    currency: { code: "UAH", name: "Ukrainian hryvnia", symbol: "₴" },
    phoneCode: "+380",
    phoneMask: "+380 ## ### ####",
  },
  {
    name: "United Arab Emirates",
    officialName: "United Arab Emirates",
    alpha2: "AE",
    alpha3: "ARE",
    numeric: "784",
    capital: "Abu Dhabi",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "الإمارات العربية المتحدة",
    languages: ["Arabic"],
    currency: {
      code: "AED",
      name: "United Arab Emirates dirham",
      symbol: "د.إ",
    },
    phoneCode: "+971",
    phoneMask: "+971 ## ### ####",
  },
  {
    name: "Uruguay",
    officialName: "Oriental Republic of Uruguay",
    alpha2: "UY",
    alpha3: "URY",
    numeric: "858",
    capital: "Montevideo",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Uruguay",
    languages: ["Spanish"],
    currency: { code: "UYU", name: "Uruguayan peso", symbol: "$" },
    phoneCode: "+598",
    phoneMask: "+598 ## ### ###",
  },
  {
    name: "Uzbekistan",
    officialName: "Republic of Uzbekistan",
    alpha2: "UZ",
    alpha3: "UZB",
    numeric: "860",
    capital: "Tashkent",
    region: "Asia",
    subregion: "Central Asia",
    continent: "Asia",
    nativeName: "Oʻzbekiston",
    languages: ["Uzbek"],
    currency: { code: "UZS", name: "Uzbekistani soʻm", symbol: "soʻm" },
    phoneCode: "+998",
    phoneMask: "+998 ## ### ####",
  },
  {
    name: "Vanuatu",
    officialName: "Republic of Vanuatu",
    alpha2: "VU",
    alpha3: "VUT",
    numeric: "548",
    capital: "Port Vila",
    region: "Oceania",
    subregion: "Melanesia",
    continent: "Oceania",
    nativeName: "Vanuatu",
    languages: ["Bislama", "English", "French"],
    currency: { code: "VUV", name: "Vanuatu vatu", symbol: "Vt" },
    phoneCode: "+678",
    phoneMask: "+678 #####",
  },
  {
    name: "Venezuela",
    officialName: "Bolivarian Republic of Venezuela",
    alpha2: "VE",
    alpha3: "VEN",
    numeric: "862",
    capital: "Caracas",
    region: "Americas",
    subregion: "South America",
    continent: "South America",
    nativeName: "Venezuela",
    languages: ["Spanish"],
    currency: {
      code: "VES",
      name: "Venezuelan bolívar",
      symbol: "Bs.",
    },
    phoneCode: "+58",
    phoneMask: "+58 ### ### ####",
  },
  {
    name: "Vietnam",
    officialName: "Socialist Republic of Vietnam",
    alpha2: "VN",
    alpha3: "VNM",
    numeric: "704",
    capital: "Hanoi",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Việt Nam",
    languages: ["Vietnamese"],
    currency: { code: "VND", name: "Vietnamese đồng", symbol: "₫" },
    phoneCode: "+84",
    phoneMask: "+84 ### ### ###",
  },
  {
    name: "Yemen",
    officialName: "Republic of Yemen",
    alpha2: "YE",
    alpha3: "YEM",
    numeric: "887",
    capital: "Sana'a",
    region: "Asia",
    subregion: "Western Asia",
    continent: "Asia",
    nativeName: "اليمن",
    languages: ["Arabic"],
    currency: { code: "YER", name: "Yemeni rial", symbol: "﷼" },
    phoneCode: "+967",
    phoneMask: "+967 ### ### ###",
  },
  {
    name: "Zambia",
    officialName: "Republic of Zambia",
    alpha2: "ZM",
    alpha3: "ZMB",
    numeric: "894",
    capital: "Lusaka",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Zambia",
    languages: ["English"],
    currency: { code: "ZMW", name: "Zambian kwacha", symbol: "ZK" },
    phoneCode: "+260",
    phoneMask: "+260 ## ### ####",
  },
  {
    name: "Zimbabwe",
    officialName: "Republic of Zimbabwe",
    alpha2: "ZW",
    alpha3: "ZWE",
    numeric: "716",
    capital: "Harare",
    region: "Africa",
    subregion: "Eastern Africa",
    continent: "Africa",
    nativeName: "Zimbabwe",
    languages: ["English", "Shona", "Ndebele"],
    currency: { code: "ZWL", name: "Zimbabwean dollar", symbol: "$" },
    phoneCode: "+263",
    phoneMask: "+263 ## ### ####",
  },
  {
    name: "Timor-Leste",
    officialName: "Democratic Republic of Timor-Leste",
    alpha2: "TL",
    alpha3: "TLS",
    numeric: "626",
    capital: "Dili",
    region: "Asia",
    subregion: "South-Eastern Asia",
    continent: "Asia",
    nativeName: "Timor-Leste",
    languages: ["Portuguese", "Tetum"],
    currency: {
      code: "USD",
      name: "United States dollar",
      symbol: "$",
    },
    phoneCode: "+670",
    phoneMask: "+670 ### ####",
  },
] as const;
